import type { SintheticResolverInfo } from '../../../tsTypes';

const info = {
  fieldName: 'node',
  fieldNodes: [
    {
      kind: 'Field',
      name: { kind: 'Name', value: 'node', loc: { start: 16, end: 20 } },
      arguments: [
        {
          kind: 'Argument',
          name: { kind: 'Name', value: 'id', loc: { start: 21, end: 23 } },
          value: {
            kind: 'StringValue',
            value: 'NWYxMDEzMTQ4NGZiYjIwMDNiZjFiNTkxOlJlc3RhdXJhbnQ6Rm9yVmlldw==',
            block: false,
            loc: { start: 25, end: 87 },
          },
          loc: { start: 21, end: 87 },
        },
      ],
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'id', loc: { start: 95, end: 97 } },
            arguments: [],
            directives: [],
            loc: { start: 95, end: 97 },
          },
          {
            kind: 'InlineFragment',
            typeCondition: {
              kind: 'NamedType',
              name: { kind: 'Name', value: 'RestaurantForView', loc: { start: 109, end: 126 } },
              loc: { start: 109, end: 126 },
            },
            directives: [],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'ukTitle', loc: { start: 135, end: 142 } },
                  arguments: [],
                  directives: [],
                  loc: { start: 135, end: 142 },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'commentList', loc: { start: 149, end: 160 } },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'id', loc: { start: 171, end: 173 } },
                        arguments: [],
                        directives: [],
                        loc: { start: 171, end: 173 },
                      },
                    ],
                    loc: { start: 161, end: 181 },
                  },
                  loc: { start: 149, end: 181 },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'banquetHall', loc: { start: 188, end: 199 } },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'id', loc: { start: 210, end: 212 } },
                        arguments: [],
                        directives: [],
                        loc: { start: 210, end: 212 },
                      },
                    ],
                    loc: { start: 200, end: 220 },
                  },
                  loc: { start: 188, end: 220 },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'conferenceHall', loc: { start: 227, end: 241 } },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'id', loc: { start: 252, end: 254 } },
                        arguments: [],
                        directives: [],
                        loc: { start: 252, end: 254 },
                      },
                    ],
                    loc: { start: 242, end: 262 },
                  },
                  loc: { start: 227, end: 262 },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'menu', loc: { start: 269, end: 273 } },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'id', loc: { start: 284, end: 286 } },
                        arguments: [],
                        directives: [],
                        loc: { start: 284, end: 286 },
                      },
                    ],
                    loc: { start: 274, end: 294 },
                  },
                  loc: { start: 269, end: 294 },
                },
              ],
              loc: { start: 127, end: 300 },
            },
            loc: { start: 102, end: 300 },
          },
        ],
        loc: { start: 89, end: 304 },
      },
      loc: { start: 16, end: 304 },
    },
  ],
  returnType: 'Node',
  parentType: 'Query',
  path: { key: 'node', typename: 'Query' },
  schema: {
    __validationErrors: [],
    extensions: {},
    astNode: {
      kind: 'SchemaDefinition',
      operationTypes: [
        {
          kind: 'OperationTypeDefinition',
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Query', loc: { start: 339611, end: 339616 } },
          },
          operation: 'query',
        },
        {
          kind: 'OperationTypeDefinition',
          type: {
            kind: 'NamedType',
            name: { kind: 'Name', value: 'Mutation', loc: { start: 370159, end: 370167 } },
          },
          operation: 'mutation',
        },
      ],
    },
    extensionASTNodes: [],
    _queryType: 'Query',
    _mutationType: 'Mutation',
    _directives: ['@include', '@skip', '@deprecated', '@specifiedBy'],
    _typeMap: {
      Query: 'Query',
      String: 'String',
      ID: 'ID',
      Int: 'Int',
      Boolean: 'Boolean',
      Mutation: 'Mutation',
      DateTime: 'DateTime',
      Upload: 'Upload',
      Node: 'Node',
      RegExp: 'RegExp',
      SliceInput: 'SliceInput',
      CuisinesEnumeration: 'CuisinesEnumeration',
      MenusEnumeration: 'MenusEnumeration',
      restaurantKindsEnumeration: 'restaurantKindsEnumeration',
      restaurantOffersEnumeration: 'restaurantOffersEnumeration',
      restaurantChainsEnumeration: 'restaurantChainsEnumeration',
      restaurantExtraSectionsEnumeration: 'restaurantExtraSectionsEnumeration',
      WeekdaysEnumeration: 'WeekdaysEnumeration',
      OauthServersEnumeration: 'OauthServersEnumeration',
      DishFeaturesEnumeration: 'DishFeaturesEnumeration',
      RolesEnumeration: 'RolesEnumeration',
      LangsEnumeration: 'LangsEnumeration',
      PublicationsEnumeration: 'PublicationsEnumeration',
      NewsFeedEnumeration: 'NewsFeedEnumeration',
      EventsEnumeration: 'EventsEnumeration',
      JournalEnumeration: 'JournalEnumeration',
      ToProfessionalsEnumeration: 'ToProfessionalsEnumeration',
      GeospatialPoint: 'GeospatialPoint',
      Float: 'Float',
      GeospatialPointInput: 'GeospatialPointInput',
      Comment: 'Comment',
      Dish: 'Dish',
      MinMaxInt: 'MinMaxInt',
      PhotoBlock: 'PhotoBlock',
      RestaurantCartItem: 'RestaurantCartItem',
      TextBlock: 'TextBlock',
      WorkDay: 'WorkDay',
      Illustration: 'Illustration',
      TangibleIllustration: 'TangibleIllustration',
      Logo: 'Logo',
      TangibleLogo: 'TangibleLogo',
      Photo: 'Photo',
      TangiblePhoto: 'TangiblePhoto',
      Restaurant: 'Restaurant',
      RestaurantClone: 'RestaurantClone',
      RestaurantBackup: 'RestaurantBackup',
      RestaurantCart: 'RestaurantCart',
      RestaurantLevel: 'RestaurantLevel',
      RestaurantAccess: 'RestaurantAccess',
      CommentListForRestaurant: 'CommentListForRestaurant',
      Menu: 'Menu',
      MenuBackup: 'MenuBackup',
      MenuClone: 'MenuClone',
      MenuSection: 'MenuSection',
      MenuSectionBackup: 'MenuSectionBackup',
      MenuSectionClone: 'MenuSectionClone',
      PhoneConfirmationCode: 'PhoneConfirmationCode',
      BanquetHall: 'BanquetHall',
      BanquetHallClone: 'BanquetHallClone',
      BanquetHallBackup: 'BanquetHallBackup',
      CheckedTel: 'CheckedTel',
      ConferenceHall: 'ConferenceHall',
      ConferenceHallClone: 'ConferenceHallClone',
      ConferenceHallBackup: 'ConferenceHallBackup',
      FromENtoRU: 'FromENtoRU',
      FromENtoUK: 'FromENtoUK',
      FromRUtoEN: 'FromRUtoEN',
      FromRUtoUK: 'FromRUtoUK',
      FromUKtoEN: 'FromUKtoEN',
      FromUKtoRU: 'FromUKtoRU',
      Post: 'Post',
      PostAccess: 'PostAccess',
      PostClone: 'PostClone',
      PostBackup: 'PostBackup',
      LegalEntity: 'LegalEntity',
      Invoice: 'Invoice',
      User: 'User',
      RestaurantForAllow: 'RestaurantForAllow',
      RestaurantForApprove: 'RestaurantForApprove',
      PostForApprove: 'PostForApprove',
      UserForApprove: 'UserForApprove',
      BanquetHallForCabinet: 'BanquetHallForCabinet',
      ConferenceHallForCabinet: 'ConferenceHallForCabinet',
      RestaurantForCabinet: 'RestaurantForCabinet',
      MenuForCabinet: 'MenuForCabinet',
      MenuSectionForCabinet: 'MenuSectionForCabinet',
      CommentListForRestaurantForCabinet: 'CommentListForRestaurantForCabinet',
      PostForCabinet: 'PostForCabinet',
      PostForCreate: 'PostForCreate',
      RestaurantForCreate: 'RestaurantForCreate',
      RestaurantForEdit: 'RestaurantForEdit',
      PostForEdit: 'PostForEdit',
      CommentListForRestaurantForEdit: 'CommentListForRestaurantForEdit',
      CommentListForRestaurantForGuest: 'CommentListForRestaurantForGuest',
      UserForGuest: 'UserForGuest',
      PostAccessForOwn: 'PostAccessForOwn',
      RestaurantAccessForOwn: 'RestaurantAccessForOwn',
      UserForOwn: 'UserForOwn',
      RestaurantForOwn: 'RestaurantForOwn',
      RestaurantForSetting: 'RestaurantForSetting',
      UserForSetting: 'UserForSetting',
      PostForToggle: 'PostForToggle',
      RestaurantForToggle: 'RestaurantForToggle',
      RestaurantForView: 'RestaurantForView',
      PostForView: 'PostForView',
      BanquetHallForView: 'BanquetHallForView',
      ConferenceHallForView: 'ConferenceHallForView',
      UserForView: 'UserForView',
      MenuForView: 'MenuForView',
      MenuSectionForView: 'MenuSectionForView',
      LegalEntityWhereInput: 'LegalEntityWhereInput',
      LegalEntityWhereWithoutBooleanOperationsInput:
        'LegalEntityWhereWithoutBooleanOperationsInput',
      LegalEntitySortEnum: 'LegalEntitySortEnum',
      LegalEntitySortInput: 'LegalEntitySortInput',
      PaginationInput: 'PaginationInput',
      PostWhereInput: 'PostWhereInput',
      PostWhereWithoutBooleanOperationsInput: 'PostWhereWithoutBooleanOperationsInput',
      RestaurantWhereInput: 'RestaurantWhereInput',
      RestaurantWhereWithoutBooleanOperationsInput: 'RestaurantWhereWithoutBooleanOperationsInput',
      MenuWhereInput: 'MenuWhereInput',
      MenuWhereWithoutBooleanOperationsInput: 'MenuWhereWithoutBooleanOperationsInput',
      MenuSectionWhereInput: 'MenuSectionWhereInput',
      MenuSectionWhereWithoutBooleanOperationsInput:
        'MenuSectionWhereWithoutBooleanOperationsInput',
      MenuCloneWhereInput: 'MenuCloneWhereInput',
      MenuCloneWhereWithoutBooleanOperationsInput: 'MenuCloneWhereWithoutBooleanOperationsInput',
      MenuSectionCloneWhereInput: 'MenuSectionCloneWhereInput',
      MenuSectionCloneWhereWithoutBooleanOperationsInput:
        'MenuSectionCloneWhereWithoutBooleanOperationsInput',
      MenuBackupWhereInput: 'MenuBackupWhereInput',
      MenuBackupWhereWithoutBooleanOperationsInput: 'MenuBackupWhereWithoutBooleanOperationsInput',
      MenuSectionBackupWhereInput: 'MenuSectionBackupWhereInput',
      MenuSectionBackupWhereWithoutBooleanOperationsInput:
        'MenuSectionBackupWhereWithoutBooleanOperationsInput',
      BanquetHallWhereInput: 'BanquetHallWhereInput',
      BanquetHallWhereWithoutBooleanOperationsInput:
        'BanquetHallWhereWithoutBooleanOperationsInput',
      BanquetHallCloneWhereInput: 'BanquetHallCloneWhereInput',
      BanquetHallCloneWhereWithoutBooleanOperationsInput:
        'BanquetHallCloneWhereWithoutBooleanOperationsInput',
      BanquetHallBackupWhereInput: 'BanquetHallBackupWhereInput',
      BanquetHallBackupWhereWithoutBooleanOperationsInput:
        'BanquetHallBackupWhereWithoutBooleanOperationsInput',
      ConferenceHallWhereInput: 'ConferenceHallWhereInput',
      ConferenceHallWhereWithoutBooleanOperationsInput:
        'ConferenceHallWhereWithoutBooleanOperationsInput',
      ConferenceHallCloneWhereInput: 'ConferenceHallCloneWhereInput',
      ConferenceHallCloneWhereWithoutBooleanOperationsInput:
        'ConferenceHallCloneWhereWithoutBooleanOperationsInput',
      ConferenceHallBackupWhereInput: 'ConferenceHallBackupWhereInput',
      ConferenceHallBackupWhereWithoutBooleanOperationsInput:
        'ConferenceHallBackupWhereWithoutBooleanOperationsInput',
      CommentListForRestaurantWhereInput: 'CommentListForRestaurantWhereInput',
      CommentListForRestaurantWhereWithoutBooleanOperationsInput:
        'CommentListForRestaurantWhereWithoutBooleanOperationsInput',
      RestaurantCloneWhereInput: 'RestaurantCloneWhereInput',
      RestaurantCloneWhereWithoutBooleanOperationsInput:
        'RestaurantCloneWhereWithoutBooleanOperationsInput',
      RestaurantBackupWhereInput: 'RestaurantBackupWhereInput',
      RestaurantBackupWhereWithoutBooleanOperationsInput:
        'RestaurantBackupWhereWithoutBooleanOperationsInput',
      RestaurantLevelWhereInput: 'RestaurantLevelWhereInput',
      RestaurantLevelWhereWithoutBooleanOperationsInput:
        'RestaurantLevelWhereWithoutBooleanOperationsInput',
      RestaurantAccessWhereInput: 'RestaurantAccessWhereInput',
      RestaurantAccessWhereWithoutBooleanOperationsInput:
        'RestaurantAccessWhereWithoutBooleanOperationsInput',
      PostCloneWhereInput: 'PostCloneWhereInput',
      PostCloneWhereWithoutBooleanOperationsInput: 'PostCloneWhereWithoutBooleanOperationsInput',
      PostBackupWhereInput: 'PostBackupWhereInput',
      PostBackupWhereWithoutBooleanOperationsInput: 'PostBackupWhereWithoutBooleanOperationsInput',
      PostAccessWhereInput: 'PostAccessWhereInput',
      PostAccessWhereWithoutBooleanOperationsInput: 'PostAccessWhereWithoutBooleanOperationsInput',
      PostSortEnum: 'PostSortEnum',
      PostSortInput: 'PostSortInput',
      MenuSectionSortEnum: 'MenuSectionSortEnum',
      MenuSectionSortInput: 'MenuSectionSortInput',
      MenuSectionBackupSortEnum: 'MenuSectionBackupSortEnum',
      MenuSectionBackupSortInput: 'MenuSectionBackupSortInput',
      MenuSectionCloneSortEnum: 'MenuSectionCloneSortEnum',
      MenuSectionCloneSortInput: 'MenuSectionCloneSortInput',
      RestaurantSortEnum: 'RestaurantSortEnum',
      RestaurantSortInput: 'RestaurantSortInput',
      RestaurantGeospatialFieldNamesEnum: 'RestaurantGeospatialFieldNamesEnum',
      RestaurantNearInput: 'RestaurantNearInput',
      PostForCabinetWhereInput: 'PostForCabinetWhereInput',
      PostForCabinetWhereWithoutBooleanOperationsInput:
        'PostForCabinetWhereWithoutBooleanOperationsInput',
      RestaurantForCabinetWhereInput: 'RestaurantForCabinetWhereInput',
      RestaurantForCabinetWhereWithoutBooleanOperationsInput:
        'RestaurantForCabinetWhereWithoutBooleanOperationsInput',
      MenuForCabinetWhereInput: 'MenuForCabinetWhereInput',
      MenuForCabinetWhereWithoutBooleanOperationsInput:
        'MenuForCabinetWhereWithoutBooleanOperationsInput',
      MenuSectionForCabinetWhereInput: 'MenuSectionForCabinetWhereInput',
      MenuSectionForCabinetWhereWithoutBooleanOperationsInput:
        'MenuSectionForCabinetWhereWithoutBooleanOperationsInput',
      BanquetHallForCabinetWhereInput: 'BanquetHallForCabinetWhereInput',
      BanquetHallForCabinetWhereWithoutBooleanOperationsInput:
        'BanquetHallForCabinetWhereWithoutBooleanOperationsInput',
      ConferenceHallForCabinetWhereInput: 'ConferenceHallForCabinetWhereInput',
      ConferenceHallForCabinetWhereWithoutBooleanOperationsInput:
        'ConferenceHallForCabinetWhereWithoutBooleanOperationsInput',
      CommentListForRestaurantForCabinetWhereInput: 'CommentListForRestaurantForCabinetWhereInput',
      CommentListForRestaurantForCabinetWhereWithoutBooleanOperationsInput:
        'CommentListForRestaurantForCabinetWhereWithoutBooleanOperationsInput',
      RestaurantAccessForOwnWhereInput: 'RestaurantAccessForOwnWhereInput',
      RestaurantAccessForOwnWhereWithoutBooleanOperationsInput:
        'RestaurantAccessForOwnWhereWithoutBooleanOperationsInput',
      PostAccessForOwnWhereInput: 'PostAccessForOwnWhereInput',
      PostAccessForOwnWhereWithoutBooleanOperationsInput:
        'PostAccessForOwnWhereWithoutBooleanOperationsInput',
      PostForCabinetSortEnum: 'PostForCabinetSortEnum',
      PostForCabinetSortInput: 'PostForCabinetSortInput',
      RestaurantForCabinetSortEnum: 'RestaurantForCabinetSortEnum',
      RestaurantForCabinetSortInput: 'RestaurantForCabinetSortInput',
      RestaurantForCabinetGeospatialFieldNamesEnum: 'RestaurantForCabinetGeospatialFieldNamesEnum',
      RestaurantForCabinetNearInput: 'RestaurantForCabinetNearInput',
      MenuSectionForCabinetSortEnum: 'MenuSectionForCabinetSortEnum',
      MenuSectionForCabinetSortInput: 'MenuSectionForCabinetSortInput',
      PostForViewWhereInput: 'PostForViewWhereInput',
      PostForViewWhereWithoutBooleanOperationsInput:
        'PostForViewWhereWithoutBooleanOperationsInput',
      PostForViewSortEnum: 'PostForViewSortEnum',
      PostForViewSortInput: 'PostForViewSortInput',
      MenuSectionForViewWhereInput: 'MenuSectionForViewWhereInput',
      MenuSectionForViewWhereWithoutBooleanOperationsInput:
        'MenuSectionForViewWhereWithoutBooleanOperationsInput',
      MenuForViewWhereInput: 'MenuForViewWhereInput',
      MenuForViewWhereWithoutBooleanOperationsInput:
        'MenuForViewWhereWithoutBooleanOperationsInput',
      RestaurantForViewWhereInput: 'RestaurantForViewWhereInput',
      RestaurantForViewWhereWithoutBooleanOperationsInput:
        'RestaurantForViewWhereWithoutBooleanOperationsInput',
      BanquetHallForViewWhereInput: 'BanquetHallForViewWhereInput',
      BanquetHallForViewWhereWithoutBooleanOperationsInput:
        'BanquetHallForViewWhereWithoutBooleanOperationsInput',
      ConferenceHallForViewWhereInput: 'ConferenceHallForViewWhereInput',
      ConferenceHallForViewWhereWithoutBooleanOperationsInput:
        'ConferenceHallForViewWhereWithoutBooleanOperationsInput',
      CommentListForRestaurantForGuestWhereInput: 'CommentListForRestaurantForGuestWhereInput',
      CommentListForRestaurantForGuestWhereWithoutBooleanOperationsInput:
        'CommentListForRestaurantForGuestWhereWithoutBooleanOperationsInput',
      MenuSectionForViewSortEnum: 'MenuSectionForViewSortEnum',
      MenuSectionForViewSortInput: 'MenuSectionForViewSortInput',
      RestaurantWhereOneInput: 'RestaurantWhereOneInput',
      RestaurantCloneWhereOneInput: 'RestaurantCloneWhereOneInput',
      RestaurantBackupWhereOneInput: 'RestaurantBackupWhereOneInput',
      RestaurantCartWhereOneInput: 'RestaurantCartWhereOneInput',
      RestaurantLevelWhereOneInput: 'RestaurantLevelWhereOneInput',
      RestaurantAccessWhereOneInput: 'RestaurantAccessWhereOneInput',
      CommentListForRestaurantWhereOneInput: 'CommentListForRestaurantWhereOneInput',
      MenuWhereOneInput: 'MenuWhereOneInput',
      MenuBackupWhereOneInput: 'MenuBackupWhereOneInput',
      MenuCloneWhereOneInput: 'MenuCloneWhereOneInput',
      MenuSectionWhereOneInput: 'MenuSectionWhereOneInput',
      MenuSectionBackupWhereOneInput: 'MenuSectionBackupWhereOneInput',
      MenuSectionCloneWhereOneInput: 'MenuSectionCloneWhereOneInput',
      PhoneConfirmationCodeWhereOneInput: 'PhoneConfirmationCodeWhereOneInput',
      BanquetHallWhereOneInput: 'BanquetHallWhereOneInput',
      BanquetHallCloneWhereOneInput: 'BanquetHallCloneWhereOneInput',
      BanquetHallBackupWhereOneInput: 'BanquetHallBackupWhereOneInput',
      CheckedTelWhereOneInput: 'CheckedTelWhereOneInput',
      ConferenceHallWhereOneInput: 'ConferenceHallWhereOneInput',
      ConferenceHallCloneWhereOneInput: 'ConferenceHallCloneWhereOneInput',
      ConferenceHallBackupWhereOneInput: 'ConferenceHallBackupWhereOneInput',
      FromENtoRUWhereOneInput: 'FromENtoRUWhereOneInput',
      FromENtoUKWhereOneInput: 'FromENtoUKWhereOneInput',
      FromRUtoENWhereOneInput: 'FromRUtoENWhereOneInput',
      FromRUtoUKWhereOneInput: 'FromRUtoUKWhereOneInput',
      FromUKtoENWhereOneInput: 'FromUKtoENWhereOneInput',
      FromUKtoRUWhereOneInput: 'FromUKtoRUWhereOneInput',
      PostWhereOneInput: 'PostWhereOneInput',
      PostAccessWhereOneInput: 'PostAccessWhereOneInput',
      PostCloneWhereOneInput: 'PostCloneWhereOneInput',
      PostBackupWhereOneInput: 'PostBackupWhereOneInput',
      LegalEntityWhereOneInput: 'LegalEntityWhereOneInput',
      InvoiceWhereOneInput: 'InvoiceWhereOneInput',
      UserWhereOneInput: 'UserWhereOneInput',
      RestaurantCloneSortEnum: 'RestaurantCloneSortEnum',
      RestaurantCloneSortInput: 'RestaurantCloneSortInput',
      RestaurantCloneGeospatialFieldNamesEnum: 'RestaurantCloneGeospatialFieldNamesEnum',
      RestaurantCloneNearInput: 'RestaurantCloneNearInput',
      RestaurantBackupSortEnum: 'RestaurantBackupSortEnum',
      RestaurantBackupSortInput: 'RestaurantBackupSortInput',
      RestaurantBackupGeospatialFieldNamesEnum: 'RestaurantBackupGeospatialFieldNamesEnum',
      RestaurantBackupNearInput: 'RestaurantBackupNearInput',
      RestaurantCartWhereInput: 'RestaurantCartWhereInput',
      RestaurantCartWhereWithoutBooleanOperationsInput:
        'RestaurantCartWhereWithoutBooleanOperationsInput',
      RestaurantCartSortEnum: 'RestaurantCartSortEnum',
      RestaurantCartSortInput: 'RestaurantCartSortInput',
      RestaurantLevelSortEnum: 'RestaurantLevelSortEnum',
      RestaurantLevelSortInput: 'RestaurantLevelSortInput',
      RestaurantAccessSortEnum: 'RestaurantAccessSortEnum',
      RestaurantAccessSortInput: 'RestaurantAccessSortInput',
      CommentListForRestaurantSortEnum: 'CommentListForRestaurantSortEnum',
      CommentListForRestaurantSortInput: 'CommentListForRestaurantSortInput',
      MenuSortEnum: 'MenuSortEnum',
      MenuSortInput: 'MenuSortInput',
      MenuBackupSortEnum: 'MenuBackupSortEnum',
      MenuBackupSortInput: 'MenuBackupSortInput',
      MenuCloneSortEnum: 'MenuCloneSortEnum',
      MenuCloneSortInput: 'MenuCloneSortInput',
      PhoneConfirmationCodeWhereInput: 'PhoneConfirmationCodeWhereInput',
      PhoneConfirmationCodeWhereWithoutBooleanOperationsInput:
        'PhoneConfirmationCodeWhereWithoutBooleanOperationsInput',
      PhoneConfirmationCodeSortEnum: 'PhoneConfirmationCodeSortEnum',
      PhoneConfirmationCodeSortInput: 'PhoneConfirmationCodeSortInput',
      BanquetHallSortEnum: 'BanquetHallSortEnum',
      BanquetHallSortInput: 'BanquetHallSortInput',
      BanquetHallCloneSortEnum: 'BanquetHallCloneSortEnum',
      BanquetHallCloneSortInput: 'BanquetHallCloneSortInput',
      BanquetHallBackupSortEnum: 'BanquetHallBackupSortEnum',
      BanquetHallBackupSortInput: 'BanquetHallBackupSortInput',
      CheckedTelWhereInput: 'CheckedTelWhereInput',
      CheckedTelWhereWithoutBooleanOperationsInput: 'CheckedTelWhereWithoutBooleanOperationsInput',
      CheckedTelSortEnum: 'CheckedTelSortEnum',
      CheckedTelSortInput: 'CheckedTelSortInput',
      ConferenceHallSortEnum: 'ConferenceHallSortEnum',
      ConferenceHallSortInput: 'ConferenceHallSortInput',
      ConferenceHallCloneSortEnum: 'ConferenceHallCloneSortEnum',
      ConferenceHallCloneSortInput: 'ConferenceHallCloneSortInput',
      ConferenceHallBackupSortEnum: 'ConferenceHallBackupSortEnum',
      ConferenceHallBackupSortInput: 'ConferenceHallBackupSortInput',
      FromENtoRUWhereInput: 'FromENtoRUWhereInput',
      FromENtoRUWhereWithoutBooleanOperationsInput: 'FromENtoRUWhereWithoutBooleanOperationsInput',
      FromENtoRUSortEnum: 'FromENtoRUSortEnum',
      FromENtoRUSortInput: 'FromENtoRUSortInput',
      FromENtoUKWhereInput: 'FromENtoUKWhereInput',
      FromENtoUKWhereWithoutBooleanOperationsInput: 'FromENtoUKWhereWithoutBooleanOperationsInput',
      FromENtoUKSortEnum: 'FromENtoUKSortEnum',
      FromENtoUKSortInput: 'FromENtoUKSortInput',
      FromRUtoENWhereInput: 'FromRUtoENWhereInput',
      FromRUtoENWhereWithoutBooleanOperationsInput: 'FromRUtoENWhereWithoutBooleanOperationsInput',
      FromRUtoENSortEnum: 'FromRUtoENSortEnum',
      FromRUtoENSortInput: 'FromRUtoENSortInput',
      FromRUtoUKWhereInput: 'FromRUtoUKWhereInput',
      FromRUtoUKWhereWithoutBooleanOperationsInput: 'FromRUtoUKWhereWithoutBooleanOperationsInput',
      FromRUtoUKSortEnum: 'FromRUtoUKSortEnum',
      FromRUtoUKSortInput: 'FromRUtoUKSortInput',
      FromUKtoENWhereInput: 'FromUKtoENWhereInput',
      FromUKtoENWhereWithoutBooleanOperationsInput: 'FromUKtoENWhereWithoutBooleanOperationsInput',
      FromUKtoENSortEnum: 'FromUKtoENSortEnum',
      FromUKtoENSortInput: 'FromUKtoENSortInput',
      FromUKtoRUWhereInput: 'FromUKtoRUWhereInput',
      FromUKtoRUWhereWithoutBooleanOperationsInput: 'FromUKtoRUWhereWithoutBooleanOperationsInput',
      FromUKtoRUSortEnum: 'FromUKtoRUSortEnum',
      FromUKtoRUSortInput: 'FromUKtoRUSortInput',
      PostAccessSortEnum: 'PostAccessSortEnum',
      PostAccessSortInput: 'PostAccessSortInput',
      PostCloneSortEnum: 'PostCloneSortEnum',
      PostCloneSortInput: 'PostCloneSortInput',
      PostBackupSortEnum: 'PostBackupSortEnum',
      PostBackupSortInput: 'PostBackupSortInput',
      InvoiceWhereInput: 'InvoiceWhereInput',
      InvoiceWhereWithoutBooleanOperationsInput: 'InvoiceWhereWithoutBooleanOperationsInput',
      InvoiceSortEnum: 'InvoiceSortEnum',
      InvoiceSortInput: 'InvoiceSortInput',
      UserWhereInput: 'UserWhereInput',
      UserWhereWithoutBooleanOperationsInput: 'UserWhereWithoutBooleanOperationsInput',
      UserSortEnum: 'UserSortEnum',
      UserSortInput: 'UserSortInput',
      RestaurantTextNamesEnum: 'RestaurantTextNamesEnum',
      RestaurantDistinctValuesOptionsInput: 'RestaurantDistinctValuesOptionsInput',
      RestaurantCloneTextNamesEnum: 'RestaurantCloneTextNamesEnum',
      RestaurantCloneDistinctValuesOptionsInput: 'RestaurantCloneDistinctValuesOptionsInput',
      RestaurantBackupTextNamesEnum: 'RestaurantBackupTextNamesEnum',
      RestaurantBackupDistinctValuesOptionsInput: 'RestaurantBackupDistinctValuesOptionsInput',
      RestaurantAccessTextNamesEnum: 'RestaurantAccessTextNamesEnum',
      RestaurantAccessDistinctValuesOptionsInput: 'RestaurantAccessDistinctValuesOptionsInput',
      MenuTextNamesEnum: 'MenuTextNamesEnum',
      MenuDistinctValuesOptionsInput: 'MenuDistinctValuesOptionsInput',
      MenuBackupTextNamesEnum: 'MenuBackupTextNamesEnum',
      MenuBackupDistinctValuesOptionsInput: 'MenuBackupDistinctValuesOptionsInput',
      MenuCloneTextNamesEnum: 'MenuCloneTextNamesEnum',
      MenuCloneDistinctValuesOptionsInput: 'MenuCloneDistinctValuesOptionsInput',
      MenuSectionTextNamesEnum: 'MenuSectionTextNamesEnum',
      MenuSectionDistinctValuesOptionsInput: 'MenuSectionDistinctValuesOptionsInput',
      MenuSectionBackupTextNamesEnum: 'MenuSectionBackupTextNamesEnum',
      MenuSectionBackupDistinctValuesOptionsInput: 'MenuSectionBackupDistinctValuesOptionsInput',
      MenuSectionCloneTextNamesEnum: 'MenuSectionCloneTextNamesEnum',
      MenuSectionCloneDistinctValuesOptionsInput: 'MenuSectionCloneDistinctValuesOptionsInput',
      PhoneConfirmationCodeTextNamesEnum: 'PhoneConfirmationCodeTextNamesEnum',
      PhoneConfirmationCodeDistinctValuesOptionsInput:
        'PhoneConfirmationCodeDistinctValuesOptionsInput',
      BanquetHallTextNamesEnum: 'BanquetHallTextNamesEnum',
      BanquetHallDistinctValuesOptionsInput: 'BanquetHallDistinctValuesOptionsInput',
      BanquetHallCloneTextNamesEnum: 'BanquetHallCloneTextNamesEnum',
      BanquetHallCloneDistinctValuesOptionsInput: 'BanquetHallCloneDistinctValuesOptionsInput',
      BanquetHallBackupTextNamesEnum: 'BanquetHallBackupTextNamesEnum',
      BanquetHallBackupDistinctValuesOptionsInput: 'BanquetHallBackupDistinctValuesOptionsInput',
      CheckedTelTextNamesEnum: 'CheckedTelTextNamesEnum',
      CheckedTelDistinctValuesOptionsInput: 'CheckedTelDistinctValuesOptionsInput',
      ConferenceHallTextNamesEnum: 'ConferenceHallTextNamesEnum',
      ConferenceHallDistinctValuesOptionsInput: 'ConferenceHallDistinctValuesOptionsInput',
      ConferenceHallCloneTextNamesEnum: 'ConferenceHallCloneTextNamesEnum',
      ConferenceHallCloneDistinctValuesOptionsInput:
        'ConferenceHallCloneDistinctValuesOptionsInput',
      ConferenceHallBackupTextNamesEnum: 'ConferenceHallBackupTextNamesEnum',
      ConferenceHallBackupDistinctValuesOptionsInput:
        'ConferenceHallBackupDistinctValuesOptionsInput',
      FromENtoRUTextNamesEnum: 'FromENtoRUTextNamesEnum',
      FromENtoRUDistinctValuesOptionsInput: 'FromENtoRUDistinctValuesOptionsInput',
      FromENtoUKTextNamesEnum: 'FromENtoUKTextNamesEnum',
      FromENtoUKDistinctValuesOptionsInput: 'FromENtoUKDistinctValuesOptionsInput',
      FromRUtoENTextNamesEnum: 'FromRUtoENTextNamesEnum',
      FromRUtoENDistinctValuesOptionsInput: 'FromRUtoENDistinctValuesOptionsInput',
      FromRUtoUKTextNamesEnum: 'FromRUtoUKTextNamesEnum',
      FromRUtoUKDistinctValuesOptionsInput: 'FromRUtoUKDistinctValuesOptionsInput',
      FromUKtoENTextNamesEnum: 'FromUKtoENTextNamesEnum',
      FromUKtoENDistinctValuesOptionsInput: 'FromUKtoENDistinctValuesOptionsInput',
      FromUKtoRUTextNamesEnum: 'FromUKtoRUTextNamesEnum',
      FromUKtoRUDistinctValuesOptionsInput: 'FromUKtoRUDistinctValuesOptionsInput',
      PostTextNamesEnum: 'PostTextNamesEnum',
      PostDistinctValuesOptionsInput: 'PostDistinctValuesOptionsInput',
      PostAccessTextNamesEnum: 'PostAccessTextNamesEnum',
      PostAccessDistinctValuesOptionsInput: 'PostAccessDistinctValuesOptionsInput',
      PostCloneTextNamesEnum: 'PostCloneTextNamesEnum',
      PostCloneDistinctValuesOptionsInput: 'PostCloneDistinctValuesOptionsInput',
      PostBackupTextNamesEnum: 'PostBackupTextNamesEnum',
      PostBackupDistinctValuesOptionsInput: 'PostBackupDistinctValuesOptionsInput',
      LegalEntityTextNamesEnum: 'LegalEntityTextNamesEnum',
      LegalEntityDistinctValuesOptionsInput: 'LegalEntityDistinctValuesOptionsInput',
      InvoiceTextNamesEnum: 'InvoiceTextNamesEnum',
      InvoiceDistinctValuesOptionsInput: 'InvoiceDistinctValuesOptionsInput',
      UserTextNamesEnum: 'UserTextNamesEnum',
      UserDistinctValuesOptionsInput: 'UserDistinctValuesOptionsInput',
      FileWhereInput: 'FileWhereInput',
      FileWhereOneInput: 'FileWhereOneInput',
      RestaurantWhereByUniqueInput: 'RestaurantWhereByUniqueInput',
      RestaurantCloneWhereByUniqueInput: 'RestaurantCloneWhereByUniqueInput',
      RestaurantBackupWhereByUniqueInput: 'RestaurantBackupWhereByUniqueInput',
      RestaurantCartWhereByUniqueInput: 'RestaurantCartWhereByUniqueInput',
      RestaurantLevelWhereByUniqueInput: 'RestaurantLevelWhereByUniqueInput',
      RestaurantAccessWhereByUniqueInput: 'RestaurantAccessWhereByUniqueInput',
      CommentListForRestaurantWhereByUniqueInput: 'CommentListForRestaurantWhereByUniqueInput',
      MenuWhereByUniqueInput: 'MenuWhereByUniqueInput',
      MenuBackupWhereByUniqueInput: 'MenuBackupWhereByUniqueInput',
      MenuCloneWhereByUniqueInput: 'MenuCloneWhereByUniqueInput',
      MenuSectionWhereByUniqueInput: 'MenuSectionWhereByUniqueInput',
      MenuSectionBackupWhereByUniqueInput: 'MenuSectionBackupWhereByUniqueInput',
      MenuSectionCloneWhereByUniqueInput: 'MenuSectionCloneWhereByUniqueInput',
      PhoneConfirmationCodeWhereByUniqueInput: 'PhoneConfirmationCodeWhereByUniqueInput',
      BanquetHallWhereByUniqueInput: 'BanquetHallWhereByUniqueInput',
      BanquetHallCloneWhereByUniqueInput: 'BanquetHallCloneWhereByUniqueInput',
      BanquetHallBackupWhereByUniqueInput: 'BanquetHallBackupWhereByUniqueInput',
      CheckedTelWhereByUniqueInput: 'CheckedTelWhereByUniqueInput',
      ConferenceHallWhereByUniqueInput: 'ConferenceHallWhereByUniqueInput',
      ConferenceHallCloneWhereByUniqueInput: 'ConferenceHallCloneWhereByUniqueInput',
      ConferenceHallBackupWhereByUniqueInput: 'ConferenceHallBackupWhereByUniqueInput',
      FromENtoRUWhereByUniqueInput: 'FromENtoRUWhereByUniqueInput',
      FromENtoUKWhereByUniqueInput: 'FromENtoUKWhereByUniqueInput',
      FromRUtoENWhereByUniqueInput: 'FromRUtoENWhereByUniqueInput',
      FromRUtoUKWhereByUniqueInput: 'FromRUtoUKWhereByUniqueInput',
      FromUKtoENWhereByUniqueInput: 'FromUKtoENWhereByUniqueInput',
      FromUKtoRUWhereByUniqueInput: 'FromUKtoRUWhereByUniqueInput',
      PostWhereByUniqueInput: 'PostWhereByUniqueInput',
      PostAccessWhereByUniqueInput: 'PostAccessWhereByUniqueInput',
      PostCloneWhereByUniqueInput: 'PostCloneWhereByUniqueInput',
      PostBackupWhereByUniqueInput: 'PostBackupWhereByUniqueInput',
      LegalEntityWhereByUniqueInput: 'LegalEntityWhereByUniqueInput',
      InvoiceWhereByUniqueInput: 'InvoiceWhereByUniqueInput',
      UserWhereByUniqueInput: 'UserWhereByUniqueInput',
      RestaurantCopyWhereOnesInput: 'RestaurantCopyWhereOnesInput',
      copyRestaurantThroughmenuOptionsEnum: 'copyRestaurantThroughmenuOptionsEnum',
      copyRestaurantThroughbanquetHallOptionsEnum: 'copyRestaurantThroughbanquetHallOptionsEnum',
      copyRestaurantThroughconferenceHallOptionsEnum:
        'copyRestaurantThroughconferenceHallOptionsEnum',
      copyRestaurantThroughpostsOptionsEnum: 'copyRestaurantThroughpostsOptionsEnum',
      copyRestaurantThroughownPostsOptionsEnum: 'copyRestaurantThroughownPostsOptionsEnum',
      copyRestaurantThroughcloneOptionsEnum: 'copyRestaurantThroughcloneOptionsEnum',
      copyRestaurantThroughbackupOptionsEnum: 'copyRestaurantThroughbackupOptionsEnum',
      copyRestaurantThroughlevelOptionsEnum: 'copyRestaurantThroughlevelOptionsEnum',
      copyRestaurantThroughmenuOptionInput: 'copyRestaurantThroughmenuOptionInput',
      copyRestaurantThroughbanquetHallOptionInput: 'copyRestaurantThroughbanquetHallOptionInput',
      copyRestaurantThroughconferenceHallOptionInput:
        'copyRestaurantThroughconferenceHallOptionInput',
      copyRestaurantThroughpostsOptionInput: 'copyRestaurantThroughpostsOptionInput',
      copyRestaurantThroughownPostsOptionInput: 'copyRestaurantThroughownPostsOptionInput',
      copyRestaurantThroughcloneOptionInput: 'copyRestaurantThroughcloneOptionInput',
      copyRestaurantThroughbackupOptionInput: 'copyRestaurantThroughbackupOptionInput',
      copyRestaurantThroughlevelOptionInput: 'copyRestaurantThroughlevelOptionInput',
      copyRestaurantOptionsInput: 'copyRestaurantOptionsInput',
      RestaurantWhereOneToCopyInput: 'RestaurantWhereOneToCopyInput',
      RestaurantCloneCopyWhereOnesInput: 'RestaurantCloneCopyWhereOnesInput',
      copyRestaurantCloneThroughoriginalOptionsEnum:
        'copyRestaurantCloneThroughoriginalOptionsEnum',
      copyRestaurantCloneThroughoriginalOptionInput:
        'copyRestaurantCloneThroughoriginalOptionInput',
      copyRestaurantCloneOptionsInput: 'copyRestaurantCloneOptionsInput',
      RestaurantBackupCopyWhereOnesInput: 'RestaurantBackupCopyWhereOnesInput',
      copyRestaurantBackupThroughoriginalOptionsEnum:
        'copyRestaurantBackupThroughoriginalOptionsEnum',
      copyRestaurantBackupThroughoriginalOptionInput:
        'copyRestaurantBackupThroughoriginalOptionInput',
      copyRestaurantBackupOptionsInput: 'copyRestaurantBackupOptionsInput',
      RestaurantLevelCopyWhereOnesInput: 'RestaurantLevelCopyWhereOnesInput',
      copyRestaurantLevelThroughoriginalOptionsEnum:
        'copyRestaurantLevelThroughoriginalOptionsEnum',
      copyRestaurantLevelThroughoriginalOptionInput:
        'copyRestaurantLevelThroughoriginalOptionInput',
      copyRestaurantLevelOptionsInput: 'copyRestaurantLevelOptionsInput',
      MenuCopyWhereOnesInput: 'MenuCopyWhereOnesInput',
      copyMenuThroughrestaurantOptionsEnum: 'copyMenuThroughrestaurantOptionsEnum',
      copyMenuThroughcloneOptionsEnum: 'copyMenuThroughcloneOptionsEnum',
      copyMenuThroughbackupOptionsEnum: 'copyMenuThroughbackupOptionsEnum',
      copyMenuThroughrestaurantOptionInput: 'copyMenuThroughrestaurantOptionInput',
      copyMenuThroughcloneOptionInput: 'copyMenuThroughcloneOptionInput',
      copyMenuThroughbackupOptionInput: 'copyMenuThroughbackupOptionInput',
      copyMenuOptionsInput: 'copyMenuOptionsInput',
      MenuBackupCopyWhereOnesInput: 'MenuBackupCopyWhereOnesInput',
      copyMenuBackupThroughoriginalOptionsEnum: 'copyMenuBackupThroughoriginalOptionsEnum',
      copyMenuBackupThroughoriginalOptionInput: 'copyMenuBackupThroughoriginalOptionInput',
      copyMenuBackupOptionsInput: 'copyMenuBackupOptionsInput',
      MenuCloneCopyWhereOnesInput: 'MenuCloneCopyWhereOnesInput',
      copyMenuCloneThroughoriginalOptionsEnum: 'copyMenuCloneThroughoriginalOptionsEnum',
      copyMenuCloneThroughsectionsOptionsEnum: 'copyMenuCloneThroughsectionsOptionsEnum',
      copyMenuCloneThroughoriginalOptionInput: 'copyMenuCloneThroughoriginalOptionInput',
      copyMenuCloneThroughsectionsOptionInput: 'copyMenuCloneThroughsectionsOptionInput',
      copyMenuCloneOptionsInput: 'copyMenuCloneOptionsInput',
      MenuSectionCloneCopyWhereOnesInput: 'MenuSectionCloneCopyWhereOnesInput',
      copyMenuSectionCloneThroughmenuOptionsEnum: 'copyMenuSectionCloneThroughmenuOptionsEnum',
      copyMenuSectionCloneThroughmenuOptionInput: 'copyMenuSectionCloneThroughmenuOptionInput',
      copyMenuSectionCloneOptionsInput: 'copyMenuSectionCloneOptionsInput',
      MenuSectionCloneWhereOneToCopyInput: 'MenuSectionCloneWhereOneToCopyInput',
      BanquetHallCopyWhereOnesInput: 'BanquetHallCopyWhereOnesInput',
      copyBanquetHallThroughrestaurantOptionsEnum: 'copyBanquetHallThroughrestaurantOptionsEnum',
      copyBanquetHallThroughcloneOptionsEnum: 'copyBanquetHallThroughcloneOptionsEnum',
      copyBanquetHallThroughbackupOptionsEnum: 'copyBanquetHallThroughbackupOptionsEnum',
      copyBanquetHallThroughrestaurantOptionInput: 'copyBanquetHallThroughrestaurantOptionInput',
      copyBanquetHallThroughcloneOptionInput: 'copyBanquetHallThroughcloneOptionInput',
      copyBanquetHallThroughbackupOptionInput: 'copyBanquetHallThroughbackupOptionInput',
      copyBanquetHallOptionsInput: 'copyBanquetHallOptionsInput',
      BanquetHallCloneCopyWhereOnesInput: 'BanquetHallCloneCopyWhereOnesInput',
      copyBanquetHallCloneThroughoriginalOptionsEnum:
        'copyBanquetHallCloneThroughoriginalOptionsEnum',
      copyBanquetHallCloneThroughoriginalOptionInput:
        'copyBanquetHallCloneThroughoriginalOptionInput',
      copyBanquetHallCloneOptionsInput: 'copyBanquetHallCloneOptionsInput',
      BanquetHallBackupCopyWhereOnesInput: 'BanquetHallBackupCopyWhereOnesInput',
      copyBanquetHallBackupThroughoriginalOptionsEnum:
        'copyBanquetHallBackupThroughoriginalOptionsEnum',
      copyBanquetHallBackupThroughoriginalOptionInput:
        'copyBanquetHallBackupThroughoriginalOptionInput',
      copyBanquetHallBackupOptionsInput: 'copyBanquetHallBackupOptionsInput',
      ConferenceHallCopyWhereOnesInput: 'ConferenceHallCopyWhereOnesInput',
      copyConferenceHallThroughrestaurantOptionsEnum:
        'copyConferenceHallThroughrestaurantOptionsEnum',
      copyConferenceHallThroughcloneOptionsEnum: 'copyConferenceHallThroughcloneOptionsEnum',
      copyConferenceHallThroughbackupOptionsEnum: 'copyConferenceHallThroughbackupOptionsEnum',
      copyConferenceHallThroughrestaurantOptionInput:
        'copyConferenceHallThroughrestaurantOptionInput',
      copyConferenceHallThroughcloneOptionInput: 'copyConferenceHallThroughcloneOptionInput',
      copyConferenceHallThroughbackupOptionInput: 'copyConferenceHallThroughbackupOptionInput',
      copyConferenceHallOptionsInput: 'copyConferenceHallOptionsInput',
      ConferenceHallCloneCopyWhereOnesInput: 'ConferenceHallCloneCopyWhereOnesInput',
      copyConferenceHallCloneThroughoriginalOptionsEnum:
        'copyConferenceHallCloneThroughoriginalOptionsEnum',
      copyConferenceHallCloneThroughoriginalOptionInput:
        'copyConferenceHallCloneThroughoriginalOptionInput',
      copyConferenceHallCloneOptionsInput: 'copyConferenceHallCloneOptionsInput',
      ConferenceHallBackupCopyWhereOnesInput: 'ConferenceHallBackupCopyWhereOnesInput',
      copyConferenceHallBackupThroughoriginalOptionsEnum:
        'copyConferenceHallBackupThroughoriginalOptionsEnum',
      copyConferenceHallBackupThroughoriginalOptionInput:
        'copyConferenceHallBackupThroughoriginalOptionInput',
      copyConferenceHallBackupOptionsInput: 'copyConferenceHallBackupOptionsInput',
      PostCopyWhereOnesInput: 'PostCopyWhereOnesInput',
      copyPostThroughrestaurantsOptionsEnum: 'copyPostThroughrestaurantsOptionsEnum',
      copyPostThroughrestaurantOptionsEnum: 'copyPostThroughrestaurantOptionsEnum',
      copyPostThroughcloneOptionsEnum: 'copyPostThroughcloneOptionsEnum',
      copyPostThroughbackupOptionsEnum: 'copyPostThroughbackupOptionsEnum',
      copyPostThroughrestaurantsOptionInput: 'copyPostThroughrestaurantsOptionInput',
      copyPostThroughrestaurantOptionInput: 'copyPostThroughrestaurantOptionInput',
      copyPostThroughcloneOptionInput: 'copyPostThroughcloneOptionInput',
      copyPostThroughbackupOptionInput: 'copyPostThroughbackupOptionInput',
      copyPostOptionsInput: 'copyPostOptionsInput',
      PostWhereOneToCopyInput: 'PostWhereOneToCopyInput',
      PostCloneCopyWhereOnesInput: 'PostCloneCopyWhereOnesInput',
      copyPostCloneThroughoriginalOptionsEnum: 'copyPostCloneThroughoriginalOptionsEnum',
      copyPostCloneThroughoriginalOptionInput: 'copyPostCloneThroughoriginalOptionInput',
      copyPostCloneOptionsInput: 'copyPostCloneOptionsInput',
      PostBackupCopyWhereOnesInput: 'PostBackupCopyWhereOnesInput',
      copyPostBackupThroughoriginalOptionsEnum: 'copyPostBackupThroughoriginalOptionsEnum',
      copyPostBackupThroughoriginalOptionInput: 'copyPostBackupThroughoriginalOptionInput',
      copyPostBackupOptionsInput: 'copyPostBackupOptionsInput',
      RestaurantCreateInput: 'RestaurantCreateInput',
      RestaurantCreateThru_commentList_FieldInput: 'RestaurantCreateThru_commentList_FieldInput',
      RestaurantCreateChildInput: 'RestaurantCreateChildInput',
      RestaurantCreateOrPushChildrenInput: 'RestaurantCreateOrPushChildrenInput',
      RestaurantCreateThru_commentList_FieldChildInput:
        'RestaurantCreateThru_commentList_FieldChildInput',
      RestaurantCreateOrPushThru_commentList_FieldChildrenInput:
        'RestaurantCreateOrPushThru_commentList_FieldChildrenInput',
      MenuCreateInput: 'MenuCreateInput',
      MenuCreateThru_restaurant_FieldInput: 'MenuCreateThru_restaurant_FieldInput',
      MenuCreateChildInput: 'MenuCreateChildInput',
      MenuCreateOrPushChildrenInput: 'MenuCreateOrPushChildrenInput',
      MenuCreateThru_restaurant_FieldChildInput: 'MenuCreateThru_restaurant_FieldChildInput',
      MenuCreateOrPushThru_restaurant_FieldChildrenInput:
        'MenuCreateOrPushThru_restaurant_FieldChildrenInput',
      MenuSectionCreateInput: 'MenuSectionCreateInput',
      MenuSectionCreateThru_menu_FieldInput: 'MenuSectionCreateThru_menu_FieldInput',
      MenuSectionCreateChildInput: 'MenuSectionCreateChildInput',
      MenuSectionCreateOrPushChildrenInput: 'MenuSectionCreateOrPushChildrenInput',
      MenuSectionCreateThru_menu_FieldChildInput: 'MenuSectionCreateThru_menu_FieldChildInput',
      MenuSectionCreateOrPushThru_menu_FieldChildrenInput:
        'MenuSectionCreateOrPushThru_menu_FieldChildrenInput',
      DishCreateInput: 'DishCreateInput',
      PhotoCreateInput: 'PhotoCreateInput',
      MenuCloneCreateInput: 'MenuCloneCreateInput',
      MenuCloneCreateThru_original_FieldInput: 'MenuCloneCreateThru_original_FieldInput',
      MenuCloneCreateChildInput: 'MenuCloneCreateChildInput',
      MenuCloneCreateOrPushChildrenInput: 'MenuCloneCreateOrPushChildrenInput',
      MenuCloneCreateThru_original_FieldChildInput: 'MenuCloneCreateThru_original_FieldChildInput',
      MenuCloneCreateOrPushThru_original_FieldChildrenInput:
        'MenuCloneCreateOrPushThru_original_FieldChildrenInput',
      MenuSectionCloneCreateInput: 'MenuSectionCloneCreateInput',
      MenuSectionCloneCreateThru_menu_FieldInput: 'MenuSectionCloneCreateThru_menu_FieldInput',
      MenuSectionCloneCreateChildInput: 'MenuSectionCloneCreateChildInput',
      MenuSectionCloneCreateOrPushChildrenInput: 'MenuSectionCloneCreateOrPushChildrenInput',
      MenuSectionCloneCreateThru_menu_FieldChildInput:
        'MenuSectionCloneCreateThru_menu_FieldChildInput',
      MenuSectionCloneCreateOrPushThru_menu_FieldChildrenInput:
        'MenuSectionCloneCreateOrPushThru_menu_FieldChildrenInput',
      MenuBackupCreateInput: 'MenuBackupCreateInput',
      MenuBackupCreateThru_original_FieldInput: 'MenuBackupCreateThru_original_FieldInput',
      MenuBackupCreateChildInput: 'MenuBackupCreateChildInput',
      MenuBackupCreateOrPushChildrenInput: 'MenuBackupCreateOrPushChildrenInput',
      MenuBackupCreateThru_original_FieldChildInput:
        'MenuBackupCreateThru_original_FieldChildInput',
      MenuBackupCreateOrPushThru_original_FieldChildrenInput:
        'MenuBackupCreateOrPushThru_original_FieldChildrenInput',
      MenuSectionBackupCreateInput: 'MenuSectionBackupCreateInput',
      MenuSectionBackupCreateThru_menu_FieldInput: 'MenuSectionBackupCreateThru_menu_FieldInput',
      MenuSectionBackupCreateChildInput: 'MenuSectionBackupCreateChildInput',
      MenuSectionBackupCreateOrPushChildrenInput: 'MenuSectionBackupCreateOrPushChildrenInput',
      MenuSectionBackupCreateThru_menu_FieldChildInput:
        'MenuSectionBackupCreateThru_menu_FieldChildInput',
      MenuSectionBackupCreateOrPushThru_menu_FieldChildrenInput:
        'MenuSectionBackupCreateOrPushThru_menu_FieldChildrenInput',
      BanquetHallCreateInput: 'BanquetHallCreateInput',
      BanquetHallCreateThru_restaurant_FieldInput: 'BanquetHallCreateThru_restaurant_FieldInput',
      BanquetHallCreateChildInput: 'BanquetHallCreateChildInput',
      BanquetHallCreateOrPushChildrenInput: 'BanquetHallCreateOrPushChildrenInput',
      BanquetHallCreateThru_restaurant_FieldChildInput:
        'BanquetHallCreateThru_restaurant_FieldChildInput',
      BanquetHallCreateOrPushThru_restaurant_FieldChildrenInput:
        'BanquetHallCreateOrPushThru_restaurant_FieldChildrenInput',
      BanquetHallCloneCreateInput: 'BanquetHallCloneCreateInput',
      BanquetHallCloneCreateThru_original_FieldInput:
        'BanquetHallCloneCreateThru_original_FieldInput',
      BanquetHallCloneCreateChildInput: 'BanquetHallCloneCreateChildInput',
      BanquetHallCloneCreateOrPushChildrenInput: 'BanquetHallCloneCreateOrPushChildrenInput',
      BanquetHallCloneCreateThru_original_FieldChildInput:
        'BanquetHallCloneCreateThru_original_FieldChildInput',
      BanquetHallCloneCreateOrPushThru_original_FieldChildrenInput:
        'BanquetHallCloneCreateOrPushThru_original_FieldChildrenInput',
      BanquetHallBackupCreateInput: 'BanquetHallBackupCreateInput',
      BanquetHallBackupCreateThru_original_FieldInput:
        'BanquetHallBackupCreateThru_original_FieldInput',
      BanquetHallBackupCreateChildInput: 'BanquetHallBackupCreateChildInput',
      BanquetHallBackupCreateOrPushChildrenInput: 'BanquetHallBackupCreateOrPushChildrenInput',
      BanquetHallBackupCreateThru_original_FieldChildInput:
        'BanquetHallBackupCreateThru_original_FieldChildInput',
      BanquetHallBackupCreateOrPushThru_original_FieldChildrenInput:
        'BanquetHallBackupCreateOrPushThru_original_FieldChildrenInput',
      ConferenceHallCreateInput: 'ConferenceHallCreateInput',
      ConferenceHallCreateThru_restaurant_FieldInput:
        'ConferenceHallCreateThru_restaurant_FieldInput',
      ConferenceHallCreateChildInput: 'ConferenceHallCreateChildInput',
      ConferenceHallCreateOrPushChildrenInput: 'ConferenceHallCreateOrPushChildrenInput',
      ConferenceHallCreateThru_restaurant_FieldChildInput:
        'ConferenceHallCreateThru_restaurant_FieldChildInput',
      ConferenceHallCreateOrPushThru_restaurant_FieldChildrenInput:
        'ConferenceHallCreateOrPushThru_restaurant_FieldChildrenInput',
      ConferenceHallCloneCreateInput: 'ConferenceHallCloneCreateInput',
      ConferenceHallCloneCreateThru_original_FieldInput:
        'ConferenceHallCloneCreateThru_original_FieldInput',
      ConferenceHallCloneCreateChildInput: 'ConferenceHallCloneCreateChildInput',
      ConferenceHallCloneCreateOrPushChildrenInput: 'ConferenceHallCloneCreateOrPushChildrenInput',
      ConferenceHallCloneCreateThru_original_FieldChildInput:
        'ConferenceHallCloneCreateThru_original_FieldChildInput',
      ConferenceHallCloneCreateOrPushThru_original_FieldChildrenInput:
        'ConferenceHallCloneCreateOrPushThru_original_FieldChildrenInput',
      ConferenceHallBackupCreateInput: 'ConferenceHallBackupCreateInput',
      ConferenceHallBackupCreateThru_original_FieldInput:
        'ConferenceHallBackupCreateThru_original_FieldInput',
      ConferenceHallBackupCreateChildInput: 'ConferenceHallBackupCreateChildInput',
      ConferenceHallBackupCreateOrPushChildrenInput:
        'ConferenceHallBackupCreateOrPushChildrenInput',
      ConferenceHallBackupCreateThru_original_FieldChildInput:
        'ConferenceHallBackupCreateThru_original_FieldChildInput',
      ConferenceHallBackupCreateOrPushThru_original_FieldChildrenInput:
        'ConferenceHallBackupCreateOrPushThru_original_FieldChildrenInput',
      CommentListForRestaurantCreateInput: 'CommentListForRestaurantCreateInput',
      CommentListForRestaurantCreateThru_restaurant_FieldInput:
        'CommentListForRestaurantCreateThru_restaurant_FieldInput',
      CommentListForRestaurantCreateChildInput: 'CommentListForRestaurantCreateChildInput',
      CommentListForRestaurantCreateOrPushChildrenInput:
        'CommentListForRestaurantCreateOrPushChildrenInput',
      CommentListForRestaurantCreateThru_restaurant_FieldChildInput:
        'CommentListForRestaurantCreateThru_restaurant_FieldChildInput',
      CommentListForRestaurantCreateOrPushThru_restaurant_FieldChildrenInput:
        'CommentListForRestaurantCreateOrPushThru_restaurant_FieldChildrenInput',
      CommentCreateInput: 'CommentCreateInput',
      PostCreateInput: 'PostCreateInput',
      PostCreateChildInput: 'PostCreateChildInput',
      PostCreateOrPushChildrenInput: 'PostCreateOrPushChildrenInput',
      PostCloneCreateInput: 'PostCloneCreateInput',
      PostCloneCreateThru_original_FieldInput: 'PostCloneCreateThru_original_FieldInput',
      PostCloneCreateChildInput: 'PostCloneCreateChildInput',
      PostCloneCreateOrPushChildrenInput: 'PostCloneCreateOrPushChildrenInput',
      PostCloneCreateThru_original_FieldChildInput: 'PostCloneCreateThru_original_FieldChildInput',
      PostCloneCreateOrPushThru_original_FieldChildrenInput:
        'PostCloneCreateOrPushThru_original_FieldChildrenInput',
      TextBlockCreateInput: 'TextBlockCreateInput',
      PhotoBlockCreateInput: 'PhotoBlockCreateInput',
      IllustrationCreateInput: 'IllustrationCreateInput',
      PostBackupCreateInput: 'PostBackupCreateInput',
      PostBackupCreateThru_original_FieldInput: 'PostBackupCreateThru_original_FieldInput',
      PostBackupCreateChildInput: 'PostBackupCreateChildInput',
      PostBackupCreateOrPushChildrenInput: 'PostBackupCreateOrPushChildrenInput',
      PostBackupCreateThru_original_FieldChildInput:
        'PostBackupCreateThru_original_FieldChildInput',
      PostBackupCreateOrPushThru_original_FieldChildrenInput:
        'PostBackupCreateOrPushThru_original_FieldChildrenInput',
      PostAccessCreateInput: 'PostAccessCreateInput',
      PostAccessCreateThru_post_FieldInput: 'PostAccessCreateThru_post_FieldInput',
      PostAccessCreateChildInput: 'PostAccessCreateChildInput',
      PostAccessCreateOrPushChildrenInput: 'PostAccessCreateOrPushChildrenInput',
      PostAccessCreateThru_post_FieldChildInput: 'PostAccessCreateThru_post_FieldChildInput',
      PostAccessCreateOrPushThru_post_FieldChildrenInput:
        'PostAccessCreateOrPushThru_post_FieldChildrenInput',
      RestaurantCloneCreateInput: 'RestaurantCloneCreateInput',
      RestaurantCloneCreateThru_original_FieldInput:
        'RestaurantCloneCreateThru_original_FieldInput',
      RestaurantCloneCreateChildInput: 'RestaurantCloneCreateChildInput',
      RestaurantCloneCreateOrPushChildrenInput: 'RestaurantCloneCreateOrPushChildrenInput',
      RestaurantCloneCreateThru_original_FieldChildInput:
        'RestaurantCloneCreateThru_original_FieldChildInput',
      RestaurantCloneCreateOrPushThru_original_FieldChildrenInput:
        'RestaurantCloneCreateOrPushThru_original_FieldChildrenInput',
      WorkDayCreateInput: 'WorkDayCreateInput',
      MinMaxIntCreateInput: 'MinMaxIntCreateInput',
      LogoCreateInput: 'LogoCreateInput',
      RestaurantBackupCreateInput: 'RestaurantBackupCreateInput',
      RestaurantBackupCreateThru_original_FieldInput:
        'RestaurantBackupCreateThru_original_FieldInput',
      RestaurantBackupCreateChildInput: 'RestaurantBackupCreateChildInput',
      RestaurantBackupCreateOrPushChildrenInput: 'RestaurantBackupCreateOrPushChildrenInput',
      RestaurantBackupCreateThru_original_FieldChildInput:
        'RestaurantBackupCreateThru_original_FieldChildInput',
      RestaurantBackupCreateOrPushThru_original_FieldChildrenInput:
        'RestaurantBackupCreateOrPushThru_original_FieldChildrenInput',
      RestaurantLevelCreateInput: 'RestaurantLevelCreateInput',
      RestaurantLevelCreateThru_original_FieldInput:
        'RestaurantLevelCreateThru_original_FieldInput',
      RestaurantLevelCreateChildInput: 'RestaurantLevelCreateChildInput',
      RestaurantLevelCreateOrPushChildrenInput: 'RestaurantLevelCreateOrPushChildrenInput',
      RestaurantLevelCreateThru_original_FieldChildInput:
        'RestaurantLevelCreateThru_original_FieldChildInput',
      RestaurantLevelCreateOrPushThru_original_FieldChildrenInput:
        'RestaurantLevelCreateOrPushThru_original_FieldChildrenInput',
      LegalEntityCreateInput: 'LegalEntityCreateInput',
      LegalEntityCreateChildInput: 'LegalEntityCreateChildInput',
      LegalEntityCreateOrPushChildrenInput: 'LegalEntityCreateOrPushChildrenInput',
      RestaurantAccessCreateInput: 'RestaurantAccessCreateInput',
      RestaurantAccessCreateThru_restaurant_FieldInput:
        'RestaurantAccessCreateThru_restaurant_FieldInput',
      RestaurantAccessCreateChildInput: 'RestaurantAccessCreateChildInput',
      RestaurantAccessCreateOrPushChildrenInput: 'RestaurantAccessCreateOrPushChildrenInput',
      RestaurantAccessCreateThru_restaurant_FieldChildInput:
        'RestaurantAccessCreateThru_restaurant_FieldChildInput',
      RestaurantAccessCreateOrPushThru_restaurant_FieldChildrenInput:
        'RestaurantAccessCreateOrPushThru_restaurant_FieldChildrenInput',
      RestaurantCartCreateInput: 'RestaurantCartCreateInput',
      RestaurantCartCreateChildInput: 'RestaurantCartCreateChildInput',
      RestaurantCartCreateOrPushChildrenInput: 'RestaurantCartCreateOrPushChildrenInput',
      RestaurantCartItemCreateInput: 'RestaurantCartItemCreateInput',
      PhoneConfirmationCodeCreateInput: 'PhoneConfirmationCodeCreateInput',
      PhoneConfirmationCodeCreateChildInput: 'PhoneConfirmationCodeCreateChildInput',
      PhoneConfirmationCodeCreateOrPushChildrenInput:
        'PhoneConfirmationCodeCreateOrPushChildrenInput',
      CheckedTelCreateInput: 'CheckedTelCreateInput',
      CheckedTelCreateChildInput: 'CheckedTelCreateChildInput',
      CheckedTelCreateOrPushChildrenInput: 'CheckedTelCreateOrPushChildrenInput',
      FromENtoRUCreateInput: 'FromENtoRUCreateInput',
      FromENtoRUCreateChildInput: 'FromENtoRUCreateChildInput',
      FromENtoRUCreateOrPushChildrenInput: 'FromENtoRUCreateOrPushChildrenInput',
      FromENtoUKCreateInput: 'FromENtoUKCreateInput',
      FromENtoUKCreateChildInput: 'FromENtoUKCreateChildInput',
      FromENtoUKCreateOrPushChildrenInput: 'FromENtoUKCreateOrPushChildrenInput',
      FromRUtoENCreateInput: 'FromRUtoENCreateInput',
      FromRUtoENCreateChildInput: 'FromRUtoENCreateChildInput',
      FromRUtoENCreateOrPushChildrenInput: 'FromRUtoENCreateOrPushChildrenInput',
      FromRUtoUKCreateInput: 'FromRUtoUKCreateInput',
      FromRUtoUKCreateChildInput: 'FromRUtoUKCreateChildInput',
      FromRUtoUKCreateOrPushChildrenInput: 'FromRUtoUKCreateOrPushChildrenInput',
      FromUKtoENCreateInput: 'FromUKtoENCreateInput',
      FromUKtoENCreateChildInput: 'FromUKtoENCreateChildInput',
      FromUKtoENCreateOrPushChildrenInput: 'FromUKtoENCreateOrPushChildrenInput',
      FromUKtoRUCreateInput: 'FromUKtoRUCreateInput',
      FromUKtoRUCreateChildInput: 'FromUKtoRUCreateChildInput',
      FromUKtoRUCreateOrPushChildrenInput: 'FromUKtoRUCreateOrPushChildrenInput',
      InvoiceCreateInput: 'InvoiceCreateInput',
      InvoiceCreateChildInput: 'InvoiceCreateChildInput',
      InvoiceCreateOrPushChildrenInput: 'InvoiceCreateOrPushChildrenInput',
      UserCreateInput: 'UserCreateInput',
      UserCreateChildInput: 'UserCreateChildInput',
      UserCreateOrPushChildrenInput: 'UserCreateOrPushChildrenInput',
      deleteRestaurantWithChildrenOptionsEnum: 'deleteRestaurantWithChildrenOptionsEnum',
      deleteRestaurantWithChildrenOptionsInput: 'deleteRestaurantWithChildrenOptionsInput',
      deleteMenuWithChildrenOptionsEnum: 'deleteMenuWithChildrenOptionsEnum',
      deleteMenuWithChildrenOptionsInput: 'deleteMenuWithChildrenOptionsInput',
      deleteMenuBackupWithChildrenOptionsEnum: 'deleteMenuBackupWithChildrenOptionsEnum',
      deleteMenuBackupWithChildrenOptionsInput: 'deleteMenuBackupWithChildrenOptionsInput',
      deleteMenuCloneWithChildrenOptionsEnum: 'deleteMenuCloneWithChildrenOptionsEnum',
      deleteMenuCloneWithChildrenOptionsInput: 'deleteMenuCloneWithChildrenOptionsInput',
      deleteBanquetHallWithChildrenOptionsEnum: 'deleteBanquetHallWithChildrenOptionsEnum',
      deleteBanquetHallWithChildrenOptionsInput: 'deleteBanquetHallWithChildrenOptionsInput',
      deleteConferenceHallWithChildrenOptionsEnum: 'deleteConferenceHallWithChildrenOptionsEnum',
      deleteConferenceHallWithChildrenOptionsInput: 'deleteConferenceHallWithChildrenOptionsInput',
      deletePostWithChildrenOptionsEnum: 'deletePostWithChildrenOptionsEnum',
      deletePostWithChildrenOptionsInput: 'deletePostWithChildrenOptionsInput',
      ImportFormatEnum: 'ImportFormatEnum',
      ImportOptionsInput: 'ImportOptionsInput',
      PushIntoRestaurantInput: 'PushIntoRestaurantInput',
      RestaurantPushPositionsInput: 'RestaurantPushPositionsInput',
      PushIntoRestaurantCloneInput: 'PushIntoRestaurantCloneInput',
      RestaurantClonePushPositionsInput: 'RestaurantClonePushPositionsInput',
      PushIntoRestaurantBackupInput: 'PushIntoRestaurantBackupInput',
      RestaurantBackupPushPositionsInput: 'RestaurantBackupPushPositionsInput',
      PushIntoRestaurantCartInput: 'PushIntoRestaurantCartInput',
      RestaurantCartPushPositionsInput: 'RestaurantCartPushPositionsInput',
      PushIntoRestaurantLevelInput: 'PushIntoRestaurantLevelInput',
      RestaurantLevelPushPositionsInput: 'RestaurantLevelPushPositionsInput',
      PushIntoRestaurantAccessInput: 'PushIntoRestaurantAccessInput',
      RestaurantAccessPushPositionsInput: 'RestaurantAccessPushPositionsInput',
      PushIntoCommentListForRestaurantInput: 'PushIntoCommentListForRestaurantInput',
      CommentListForRestaurantPushPositionsInput: 'CommentListForRestaurantPushPositionsInput',
      PushIntoMenuInput: 'PushIntoMenuInput',
      MenuPushPositionsInput: 'MenuPushPositionsInput',
      PushIntoMenuBackupInput: 'PushIntoMenuBackupInput',
      MenuBackupPushPositionsInput: 'MenuBackupPushPositionsInput',
      PushIntoMenuCloneInput: 'PushIntoMenuCloneInput',
      MenuClonePushPositionsInput: 'MenuClonePushPositionsInput',
      PushIntoMenuSectionInput: 'PushIntoMenuSectionInput',
      MenuSectionPushPositionsInput: 'MenuSectionPushPositionsInput',
      PushIntoMenuSectionBackupInput: 'PushIntoMenuSectionBackupInput',
      MenuSectionBackupPushPositionsInput: 'MenuSectionBackupPushPositionsInput',
      PushIntoMenuSectionCloneInput: 'PushIntoMenuSectionCloneInput',
      MenuSectionClonePushPositionsInput: 'MenuSectionClonePushPositionsInput',
      PushIntoBanquetHallInput: 'PushIntoBanquetHallInput',
      BanquetHallPushPositionsInput: 'BanquetHallPushPositionsInput',
      PushIntoBanquetHallCloneInput: 'PushIntoBanquetHallCloneInput',
      BanquetHallClonePushPositionsInput: 'BanquetHallClonePushPositionsInput',
      PushIntoBanquetHallBackupInput: 'PushIntoBanquetHallBackupInput',
      BanquetHallBackupPushPositionsInput: 'BanquetHallBackupPushPositionsInput',
      PushIntoConferenceHallInput: 'PushIntoConferenceHallInput',
      ConferenceHallPushPositionsInput: 'ConferenceHallPushPositionsInput',
      PushIntoConferenceHallCloneInput: 'PushIntoConferenceHallCloneInput',
      ConferenceHallClonePushPositionsInput: 'ConferenceHallClonePushPositionsInput',
      PushIntoConferenceHallBackupInput: 'PushIntoConferenceHallBackupInput',
      ConferenceHallBackupPushPositionsInput: 'ConferenceHallBackupPushPositionsInput',
      PushIntoPostInput: 'PushIntoPostInput',
      PostPushPositionsInput: 'PostPushPositionsInput',
      PushIntoPostAccessInput: 'PushIntoPostAccessInput',
      PostAccessPushPositionsInput: 'PostAccessPushPositionsInput',
      PushIntoPostCloneInput: 'PushIntoPostCloneInput',
      PostClonePushPositionsInput: 'PostClonePushPositionsInput',
      PushIntoPostBackupInput: 'PushIntoPostBackupInput',
      PostBackupPushPositionsInput: 'PostBackupPushPositionsInput',
      PushIntoLegalEntityInput: 'PushIntoLegalEntityInput',
      LegalEntityPushPositionsInput: 'LegalEntityPushPositionsInput',
      PushIntoInvoiceInput: 'PushIntoInvoiceInput',
      InvoicePushPositionsInput: 'InvoicePushPositionsInput',
      PushIntoUserInput: 'PushIntoUserInput',
      UserPushPositionsInput: 'UserPushPositionsInput',
      RestaurantUpdateInput: 'RestaurantUpdateInput',
      WorkDayUpdateInput: 'WorkDayUpdateInput',
      MinMaxIntUpdateInput: 'MinMaxIntUpdateInput',
      LogoUpdateInput: 'LogoUpdateInput',
      PhotoUpdateInput: 'PhotoUpdateInput',
      RestaurantCloneUpdateInput: 'RestaurantCloneUpdateInput',
      RestaurantBackupUpdateInput: 'RestaurantBackupUpdateInput',
      RestaurantCartUpdateInput: 'RestaurantCartUpdateInput',
      RestaurantCartItemUpdateInput: 'RestaurantCartItemUpdateInput',
      DishUpdateInput: 'DishUpdateInput',
      RestaurantLevelUpdateInput: 'RestaurantLevelUpdateInput',
      RestaurantAccessUpdateInput: 'RestaurantAccessUpdateInput',
      CommentListForRestaurantUpdateInput: 'CommentListForRestaurantUpdateInput',
      CommentUpdateInput: 'CommentUpdateInput',
      MenuUpdateInput: 'MenuUpdateInput',
      MenuBackupUpdateInput: 'MenuBackupUpdateInput',
      MenuCloneUpdateInput: 'MenuCloneUpdateInput',
      MenuSectionUpdateInput: 'MenuSectionUpdateInput',
      MenuSectionBackupUpdateInput: 'MenuSectionBackupUpdateInput',
      MenuSectionCloneUpdateInput: 'MenuSectionCloneUpdateInput',
      BanquetHallUpdateInput: 'BanquetHallUpdateInput',
      BanquetHallCloneUpdateInput: 'BanquetHallCloneUpdateInput',
      BanquetHallBackupUpdateInput: 'BanquetHallBackupUpdateInput',
      CheckedTelUpdateInput: 'CheckedTelUpdateInput',
      ConferenceHallUpdateInput: 'ConferenceHallUpdateInput',
      ConferenceHallCloneUpdateInput: 'ConferenceHallCloneUpdateInput',
      ConferenceHallBackupUpdateInput: 'ConferenceHallBackupUpdateInput',
      FromENtoRUUpdateInput: 'FromENtoRUUpdateInput',
      FromENtoUKUpdateInput: 'FromENtoUKUpdateInput',
      FromRUtoENUpdateInput: 'FromRUtoENUpdateInput',
      FromRUtoUKUpdateInput: 'FromRUtoUKUpdateInput',
      FromUKtoENUpdateInput: 'FromUKtoENUpdateInput',
      FromUKtoRUUpdateInput: 'FromUKtoRUUpdateInput',
      PostUpdateInput: 'PostUpdateInput',
      TextBlockUpdateInput: 'TextBlockUpdateInput',
      PhotoBlockUpdateInput: 'PhotoBlockUpdateInput',
      IllustrationUpdateInput: 'IllustrationUpdateInput',
      PostAccessUpdateInput: 'PostAccessUpdateInput',
      PostCloneUpdateInput: 'PostCloneUpdateInput',
      PostBackupUpdateInput: 'PostBackupUpdateInput',
      LegalEntityUpdateInput: 'LegalEntityUpdateInput',
      InvoiceUpdateInput: 'InvoiceUpdateInput',
      UserUpdateInput: 'UserUpdateInput',
      UploadFilesToRestaurantInput: 'UploadFilesToRestaurantInput',
      RestaurantFileNamesEnum: 'RestaurantFileNamesEnum',
      FilesOfRestaurantOptionsInput: 'FilesOfRestaurantOptionsInput',
      RestaurantReorderUploadedInput: 'RestaurantReorderUploadedInput',
      UploadFilesToRestaurantCloneInput: 'UploadFilesToRestaurantCloneInput',
      RestaurantCloneFileNamesEnum: 'RestaurantCloneFileNamesEnum',
      FilesOfRestaurantCloneOptionsInput: 'FilesOfRestaurantCloneOptionsInput',
      RestaurantCloneReorderUploadedInput: 'RestaurantCloneReorderUploadedInput',
      UploadFilesToRestaurantBackupInput: 'UploadFilesToRestaurantBackupInput',
      RestaurantBackupFileNamesEnum: 'RestaurantBackupFileNamesEnum',
      FilesOfRestaurantBackupOptionsInput: 'FilesOfRestaurantBackupOptionsInput',
      RestaurantBackupReorderUploadedInput: 'RestaurantBackupReorderUploadedInput',
      UploadFilesToMenuSectionInput: 'UploadFilesToMenuSectionInput',
      MenuSectionFileNamesEnum: 'MenuSectionFileNamesEnum',
      FilesOfMenuSectionOptionsInput: 'FilesOfMenuSectionOptionsInput',
      MenuSectionReorderUploadedInput: 'MenuSectionReorderUploadedInput',
      UploadFilesToMenuSectionBackupInput: 'UploadFilesToMenuSectionBackupInput',
      MenuSectionBackupFileNamesEnum: 'MenuSectionBackupFileNamesEnum',
      FilesOfMenuSectionBackupOptionsInput: 'FilesOfMenuSectionBackupOptionsInput',
      MenuSectionBackupReorderUploadedInput: 'MenuSectionBackupReorderUploadedInput',
      UploadFilesToMenuSectionCloneInput: 'UploadFilesToMenuSectionCloneInput',
      MenuSectionCloneFileNamesEnum: 'MenuSectionCloneFileNamesEnum',
      FilesOfMenuSectionCloneOptionsInput: 'FilesOfMenuSectionCloneOptionsInput',
      MenuSectionCloneReorderUploadedInput: 'MenuSectionCloneReorderUploadedInput',
      UploadFilesToBanquetHallInput: 'UploadFilesToBanquetHallInput',
      BanquetHallFileNamesEnum: 'BanquetHallFileNamesEnum',
      FilesOfBanquetHallOptionsInput: 'FilesOfBanquetHallOptionsInput',
      BanquetHallReorderUploadedInput: 'BanquetHallReorderUploadedInput',
      UploadFilesToBanquetHallCloneInput: 'UploadFilesToBanquetHallCloneInput',
      BanquetHallCloneFileNamesEnum: 'BanquetHallCloneFileNamesEnum',
      FilesOfBanquetHallCloneOptionsInput: 'FilesOfBanquetHallCloneOptionsInput',
      BanquetHallCloneReorderUploadedInput: 'BanquetHallCloneReorderUploadedInput',
      UploadFilesToBanquetHallBackupInput: 'UploadFilesToBanquetHallBackupInput',
      BanquetHallBackupFileNamesEnum: 'BanquetHallBackupFileNamesEnum',
      FilesOfBanquetHallBackupOptionsInput: 'FilesOfBanquetHallBackupOptionsInput',
      BanquetHallBackupReorderUploadedInput: 'BanquetHallBackupReorderUploadedInput',
      UploadFilesToConferenceHallInput: 'UploadFilesToConferenceHallInput',
      ConferenceHallFileNamesEnum: 'ConferenceHallFileNamesEnum',
      FilesOfConferenceHallOptionsInput: 'FilesOfConferenceHallOptionsInput',
      ConferenceHallReorderUploadedInput: 'ConferenceHallReorderUploadedInput',
      UploadFilesToConferenceHallCloneInput: 'UploadFilesToConferenceHallCloneInput',
      ConferenceHallCloneFileNamesEnum: 'ConferenceHallCloneFileNamesEnum',
      FilesOfConferenceHallCloneOptionsInput: 'FilesOfConferenceHallCloneOptionsInput',
      ConferenceHallCloneReorderUploadedInput: 'ConferenceHallCloneReorderUploadedInput',
      UploadFilesToConferenceHallBackupInput: 'UploadFilesToConferenceHallBackupInput',
      ConferenceHallBackupFileNamesEnum: 'ConferenceHallBackupFileNamesEnum',
      FilesOfConferenceHallBackupOptionsInput: 'FilesOfConferenceHallBackupOptionsInput',
      ConferenceHallBackupReorderUploadedInput: 'ConferenceHallBackupReorderUploadedInput',
      UploadFilesToPostInput: 'UploadFilesToPostInput',
      PostFileNamesEnum: 'PostFileNamesEnum',
      FilesOfPostOptionsInput: 'FilesOfPostOptionsInput',
      PostReorderUploadedInput: 'PostReorderUploadedInput',
      UploadFilesToPostCloneInput: 'UploadFilesToPostCloneInput',
      PostCloneFileNamesEnum: 'PostCloneFileNamesEnum',
      FilesOfPostCloneOptionsInput: 'FilesOfPostCloneOptionsInput',
      PostCloneReorderUploadedInput: 'PostCloneReorderUploadedInput',
      UploadFilesToPostBackupInput: 'UploadFilesToPostBackupInput',
      PostBackupFileNamesEnum: 'PostBackupFileNamesEnum',
      FilesOfPostBackupOptionsInput: 'FilesOfPostBackupOptionsInput',
      PostBackupReorderUploadedInput: 'PostBackupReorderUploadedInput',
      RestaurantForApproveWhereOneInput: 'RestaurantForApproveWhereOneInput',
      RestaurantForApproveWhereInput: 'RestaurantForApproveWhereInput',
      RestaurantForApproveWhereWithoutBooleanOperationsInput:
        'RestaurantForApproveWhereWithoutBooleanOperationsInput',
      UserForApproveWhereInput: 'UserForApproveWhereInput',
      UserForApproveWhereWithoutBooleanOperationsInput:
        'UserForApproveWhereWithoutBooleanOperationsInput',
      RestaurantForApproveSortEnum: 'RestaurantForApproveSortEnum',
      RestaurantForApproveSortInput: 'RestaurantForApproveSortInput',
      RestaurantForApproveGeospatialFieldNamesEnum: 'RestaurantForApproveGeospatialFieldNamesEnum',
      RestaurantForApproveNearInput: 'RestaurantForApproveNearInput',
      PostForApproveWhereOneInput: 'PostForApproveWhereOneInput',
      PostForApproveWhereInput: 'PostForApproveWhereInput',
      PostForApproveWhereWithoutBooleanOperationsInput:
        'PostForApproveWhereWithoutBooleanOperationsInput',
      PostForApproveSortEnum: 'PostForApproveSortEnum',
      PostForApproveSortInput: 'PostForApproveSortInput',
      UserForApproveWhereOneInput: 'UserForApproveWhereOneInput',
      BanquetHallForCabinetWhereOneInput: 'BanquetHallForCabinetWhereOneInput',
      ConferenceHallForCabinetWhereOneInput: 'ConferenceHallForCabinetWhereOneInput',
      RestaurantForCabinetWhereOneInput: 'RestaurantForCabinetWhereOneInput',
      MenuForCabinetWhereOneInput: 'MenuForCabinetWhereOneInput',
      CommentListForRestaurantForCabinetWhereOneInput:
        'CommentListForRestaurantForCabinetWhereOneInput',
      PostForCabinetWhereOneInput: 'PostForCabinetWhereOneInput',
      PostForCreateCreateInput: 'PostForCreateCreateInput',
      PostForCreateCreateChildInput: 'PostForCreateCreateChildInput',
      PostForCreateCreateOrPushChildrenInput: 'PostForCreateCreateOrPushChildrenInput',
      RestaurantForCabinetCreateInput: 'RestaurantForCabinetCreateInput',
      RestaurantForCabinetCreateThru_commentList_FieldInput:
        'RestaurantForCabinetCreateThru_commentList_FieldInput',
      RestaurantForCabinetCreateChildInput: 'RestaurantForCabinetCreateChildInput',
      RestaurantForCabinetCreateOrPushChildrenInput:
        'RestaurantForCabinetCreateOrPushChildrenInput',
      RestaurantForCabinetCreateThru_commentList_FieldChildInput:
        'RestaurantForCabinetCreateThru_commentList_FieldChildInput',
      RestaurantForCabinetCreateOrPushThru_commentList_FieldChildrenInput:
        'RestaurantForCabinetCreateOrPushThru_commentList_FieldChildrenInput',
      MenuForCabinetCreateInput: 'MenuForCabinetCreateInput',
      MenuForCabinetCreateThru_restaurant_FieldInput:
        'MenuForCabinetCreateThru_restaurant_FieldInput',
      MenuForCabinetCreateChildInput: 'MenuForCabinetCreateChildInput',
      MenuForCabinetCreateOrPushChildrenInput: 'MenuForCabinetCreateOrPushChildrenInput',
      MenuForCabinetCreateThru_restaurant_FieldChildInput:
        'MenuForCabinetCreateThru_restaurant_FieldChildInput',
      MenuForCabinetCreateOrPushThru_restaurant_FieldChildrenInput:
        'MenuForCabinetCreateOrPushThru_restaurant_FieldChildrenInput',
      MenuSectionForCabinetCreateInput: 'MenuSectionForCabinetCreateInput',
      MenuSectionForCabinetCreateThru_menu_FieldInput:
        'MenuSectionForCabinetCreateThru_menu_FieldInput',
      MenuSectionForCabinetCreateChildInput: 'MenuSectionForCabinetCreateChildInput',
      MenuSectionForCabinetCreateOrPushChildrenInput:
        'MenuSectionForCabinetCreateOrPushChildrenInput',
      MenuSectionForCabinetCreateThru_menu_FieldChildInput:
        'MenuSectionForCabinetCreateThru_menu_FieldChildInput',
      MenuSectionForCabinetCreateOrPushThru_menu_FieldChildrenInput:
        'MenuSectionForCabinetCreateOrPushThru_menu_FieldChildrenInput',
      BanquetHallForCabinetCreateInput: 'BanquetHallForCabinetCreateInput',
      BanquetHallForCabinetCreateThru_restaurant_FieldInput:
        'BanquetHallForCabinetCreateThru_restaurant_FieldInput',
      BanquetHallForCabinetCreateChildInput: 'BanquetHallForCabinetCreateChildInput',
      BanquetHallForCabinetCreateOrPushChildrenInput:
        'BanquetHallForCabinetCreateOrPushChildrenInput',
      BanquetHallForCabinetCreateThru_restaurant_FieldChildInput:
        'BanquetHallForCabinetCreateThru_restaurant_FieldChildInput',
      BanquetHallForCabinetCreateOrPushThru_restaurant_FieldChildrenInput:
        'BanquetHallForCabinetCreateOrPushThru_restaurant_FieldChildrenInput',
      ConferenceHallForCabinetCreateInput: 'ConferenceHallForCabinetCreateInput',
      ConferenceHallForCabinetCreateThru_restaurant_FieldInput:
        'ConferenceHallForCabinetCreateThru_restaurant_FieldInput',
      ConferenceHallForCabinetCreateChildInput: 'ConferenceHallForCabinetCreateChildInput',
      ConferenceHallForCabinetCreateOrPushChildrenInput:
        'ConferenceHallForCabinetCreateOrPushChildrenInput',
      ConferenceHallForCabinetCreateThru_restaurant_FieldChildInput:
        'ConferenceHallForCabinetCreateThru_restaurant_FieldChildInput',
      ConferenceHallForCabinetCreateOrPushThru_restaurant_FieldChildrenInput:
        'ConferenceHallForCabinetCreateOrPushThru_restaurant_FieldChildrenInput',
      CommentListForRestaurantForCabinetCreateInput:
        'CommentListForRestaurantForCabinetCreateInput',
      CommentListForRestaurantForCabinetCreateThru_restaurant_FieldInput:
        'CommentListForRestaurantForCabinetCreateThru_restaurant_FieldInput',
      CommentListForRestaurantForCabinetCreateChildInput:
        'CommentListForRestaurantForCabinetCreateChildInput',
      CommentListForRestaurantForCabinetCreateOrPushChildrenInput:
        'CommentListForRestaurantForCabinetCreateOrPushChildrenInput',
      CommentListForRestaurantForCabinetCreateThru_restaurant_FieldChildInput:
        'CommentListForRestaurantForCabinetCreateThru_restaurant_FieldChildInput',
      CommentListForRestaurantForCabinetCreateOrPushThru_restaurant_FieldChildrenInput:
        'CommentListForRestaurantForCabinetCreateOrPushThru_restaurant_FieldChildrenInput',
      PostForCabinetCreateInput: 'PostForCabinetCreateInput',
      PostForCabinetCreateChildInput: 'PostForCabinetCreateChildInput',
      PostForCabinetCreateOrPushChildrenInput: 'PostForCabinetCreateOrPushChildrenInput',
      PostAccessForOwnCreateInput: 'PostAccessForOwnCreateInput',
      PostAccessForOwnCreateThru_post_FieldInput: 'PostAccessForOwnCreateThru_post_FieldInput',
      PostAccessForOwnCreateChildInput: 'PostAccessForOwnCreateChildInput',
      PostAccessForOwnCreateOrPushChildrenInput: 'PostAccessForOwnCreateOrPushChildrenInput',
      PostAccessForOwnCreateThru_post_FieldChildInput:
        'PostAccessForOwnCreateThru_post_FieldChildInput',
      PostAccessForOwnCreateOrPushThru_post_FieldChildrenInput:
        'PostAccessForOwnCreateOrPushThru_post_FieldChildrenInput',
      RestaurantAccessForOwnCreateInput: 'RestaurantAccessForOwnCreateInput',
      RestaurantAccessForOwnCreateThru_restaurant_FieldInput:
        'RestaurantAccessForOwnCreateThru_restaurant_FieldInput',
      RestaurantAccessForOwnCreateChildInput: 'RestaurantAccessForOwnCreateChildInput',
      RestaurantAccessForOwnCreateOrPushChildrenInput:
        'RestaurantAccessForOwnCreateOrPushChildrenInput',
      RestaurantAccessForOwnCreateThru_restaurant_FieldChildInput:
        'RestaurantAccessForOwnCreateThru_restaurant_FieldChildInput',
      RestaurantAccessForOwnCreateOrPushThru_restaurant_FieldChildrenInput:
        'RestaurantAccessForOwnCreateOrPushThru_restaurant_FieldChildrenInput',
      RestaurantForCreateCreateInput: 'RestaurantForCreateCreateInput',
      RestaurantForCreateCreateThru_commentList_FieldInput:
        'RestaurantForCreateCreateThru_commentList_FieldInput',
      RestaurantForCreateCreateChildInput: 'RestaurantForCreateCreateChildInput',
      RestaurantForCreateCreateOrPushChildrenInput: 'RestaurantForCreateCreateOrPushChildrenInput',
      RestaurantForCreateCreateThru_commentList_FieldChildInput:
        'RestaurantForCreateCreateThru_commentList_FieldChildInput',
      RestaurantForCreateCreateOrPushThru_commentList_FieldChildrenInput:
        'RestaurantForCreateCreateOrPushThru_commentList_FieldChildrenInput',
      RestaurantForEditWhereOneInput: 'RestaurantForEditWhereOneInput',
      RestaurantForEditWhereInput: 'RestaurantForEditWhereInput',
      RestaurantForEditWhereWithoutBooleanOperationsInput:
        'RestaurantForEditWhereWithoutBooleanOperationsInput',
      RestaurantForEditSortEnum: 'RestaurantForEditSortEnum',
      RestaurantForEditSortInput: 'RestaurantForEditSortInput',
      RestaurantForEditGeospatialFieldNamesEnum: 'RestaurantForEditGeospatialFieldNamesEnum',
      RestaurantForEditNearInput: 'RestaurantForEditNearInput',
      PostForEditWhereInput: 'PostForEditWhereInput',
      PostForEditWhereWithoutBooleanOperationsInput:
        'PostForEditWhereWithoutBooleanOperationsInput',
      PostForEditSortEnum: 'PostForEditSortEnum',
      PostForEditSortInput: 'PostForEditSortInput',
      CommentListForRestaurantForGuestWhereOneInput:
        'CommentListForRestaurantForGuestWhereOneInput',
      PushIntoCommentListForRestaurantForGuestInput:
        'PushIntoCommentListForRestaurantForGuestInput',
      CommentListForRestaurantForGuestPushPositionsInput:
        'CommentListForRestaurantForGuestPushPositionsInput',
      PostAccessForOwnWhereOneInput: 'PostAccessForOwnWhereOneInput',
      RestaurantAccessForOwnWhereOneInput: 'RestaurantAccessForOwnWhereOneInput',
      UserForOwnWhereOneInput: 'UserForOwnWhereOneInput',
      UserForOwnWhereByUniqueInput: 'UserForOwnWhereByUniqueInput',
      UserForOwnSortEnum: 'UserForOwnSortEnum',
      UserForOwnSortInput: 'UserForOwnSortInput',
      RestaurantForSettingWhereOneInput: 'RestaurantForSettingWhereOneInput',
      RestaurantForSettingUpdateInput: 'RestaurantForSettingUpdateInput',
      UserForSettingWhereOneInput: 'UserForSettingWhereOneInput',
      UserForSettingUpdateInput: 'UserForSettingUpdateInput',
      UserForSettingWhereInput: 'UserForSettingWhereInput',
      UserForSettingWhereWithoutBooleanOperationsInput:
        'UserForSettingWhereWithoutBooleanOperationsInput',
      UserForSettingSortEnum: 'UserForSettingSortEnum',
      UserForSettingSortInput: 'UserForSettingSortInput',
      PostForToggleWhereInput: 'PostForToggleWhereInput',
      PostForToggleWhereWithoutBooleanOperationsInput:
        'PostForToggleWhereWithoutBooleanOperationsInput',
      PostForToggleSortEnum: 'PostForToggleSortEnum',
      PostForToggleSortInput: 'PostForToggleSortInput',
      PostForToggleWhereOneInput: 'PostForToggleWhereOneInput',
      PostForToggleUpdateInput: 'PostForToggleUpdateInput',
      RestaurantForToggleWhereInput: 'RestaurantForToggleWhereInput',
      RestaurantForToggleWhereWithoutBooleanOperationsInput:
        'RestaurantForToggleWhereWithoutBooleanOperationsInput',
      RestaurantForToggleSortEnum: 'RestaurantForToggleSortEnum',
      RestaurantForToggleSortInput: 'RestaurantForToggleSortInput',
      RestaurantForToggleGeospatialFieldNamesEnum: 'RestaurantForToggleGeospatialFieldNamesEnum',
      RestaurantForToggleNearInput: 'RestaurantForToggleNearInput',
      RestaurantForToggleWhereOneInput: 'RestaurantForToggleWhereOneInput',
      RestaurantForToggleUpdateInput: 'RestaurantForToggleUpdateInput',
      RestaurantForViewSortEnum: 'RestaurantForViewSortEnum',
      RestaurantForViewSortInput: 'RestaurantForViewSortInput',
      RestaurantForViewGeospatialFieldNamesEnum: 'RestaurantForViewGeospatialFieldNamesEnum',
      RestaurantForViewNearInput: 'RestaurantForViewNearInput',
      RestaurantForViewWhereOneInput: 'RestaurantForViewWhereOneInput',
      PostForViewWhereOneInput: 'PostForViewWhereOneInput',
      BanquetHallForViewWhereOneInput: 'BanquetHallForViewWhereOneInput',
      ConferenceHallForViewWhereOneInput: 'ConferenceHallForViewWhereOneInput',
      MenuForViewWhereOneInput: 'MenuForViewWhereOneInput',
      RestaurantUpdatePermissionsInput: 'RestaurantUpdatePermissionsInput',
      __Schema: '__Schema',
      __Type: '__Type',
      __TypeKind: '__TypeKind',
      __Field: '__Field',
      __InputValue: '__InputValue',
      __EnumValue: '__EnumValue',
      __Directive: '__Directive',
      __DirectiveLocation: '__DirectiveLocation',
    },
    _subTypeMap: {
      Node: {
        TangibleIllustration: true,
        TangibleLogo: true,
        TangiblePhoto: true,
        Restaurant: true,
        RestaurantClone: true,
        RestaurantBackup: true,
        RestaurantCart: true,
        RestaurantLevel: true,
        RestaurantAccess: true,
        CommentListForRestaurant: true,
        Menu: true,
        MenuBackup: true,
        MenuClone: true,
        MenuSection: true,
        MenuSectionBackup: true,
        MenuSectionClone: true,
        PhoneConfirmationCode: true,
        BanquetHall: true,
        BanquetHallClone: true,
        BanquetHallBackup: true,
        CheckedTel: true,
        ConferenceHall: true,
        ConferenceHallClone: true,
        ConferenceHallBackup: true,
        FromENtoRU: true,
        FromENtoUK: true,
        FromRUtoEN: true,
        FromRUtoUK: true,
        FromUKtoEN: true,
        FromUKtoRU: true,
        Post: true,
        PostAccess: true,
        PostClone: true,
        PostBackup: true,
        LegalEntity: true,
        Invoice: true,
        User: true,
        RestaurantForAllow: true,
        RestaurantForApprove: true,
        PostForApprove: true,
        UserForApprove: true,
        BanquetHallForCabinet: true,
        ConferenceHallForCabinet: true,
        RestaurantForCabinet: true,
        MenuForCabinet: true,
        MenuSectionForCabinet: true,
        CommentListForRestaurantForCabinet: true,
        PostForCabinet: true,
        PostForCreate: true,
        RestaurantForCreate: true,
        RestaurantForEdit: true,
        PostForEdit: true,
        CommentListForRestaurantForEdit: true,
        CommentListForRestaurantForGuest: true,
        UserForGuest: true,
        PostAccessForOwn: true,
        RestaurantAccessForOwn: true,
        UserForOwn: true,
        RestaurantForOwn: true,
        RestaurantForSetting: true,
        UserForSetting: true,
        PostForToggle: true,
        RestaurantForToggle: true,
        RestaurantForView: true,
        PostForView: true,
        BanquetHallForView: true,
        ConferenceHallForView: true,
        UserForView: true,
        MenuForView: true,
        MenuSectionForView: true,
      },
    },
    _implementationsMap: {
      Node: {
        objects: [
          'TangibleIllustration',
          'TangibleLogo',
          'TangiblePhoto',
          'Restaurant',
          'RestaurantClone',
          'RestaurantBackup',
          'RestaurantCart',
          'RestaurantLevel',
          'RestaurantAccess',
          'CommentListForRestaurant',
          'Menu',
          'MenuBackup',
          'MenuClone',
          'MenuSection',
          'MenuSectionBackup',
          'MenuSectionClone',
          'PhoneConfirmationCode',
          'BanquetHall',
          'BanquetHallClone',
          'BanquetHallBackup',
          'CheckedTel',
          'ConferenceHall',
          'ConferenceHallClone',
          'ConferenceHallBackup',
          'FromENtoRU',
          'FromENtoUK',
          'FromRUtoEN',
          'FromRUtoUK',
          'FromUKtoEN',
          'FromUKtoRU',
          'Post',
          'PostAccess',
          'PostClone',
          'PostBackup',
          'LegalEntity',
          'Invoice',
          'User',
          'RestaurantForAllow',
          'RestaurantForApprove',
          'PostForApprove',
          'UserForApprove',
          'BanquetHallForCabinet',
          'ConferenceHallForCabinet',
          'RestaurantForCabinet',
          'MenuForCabinet',
          'MenuSectionForCabinet',
          'CommentListForRestaurantForCabinet',
          'PostForCabinet',
          'PostForCreate',
          'RestaurantForCreate',
          'RestaurantForEdit',
          'PostForEdit',
          'CommentListForRestaurantForEdit',
          'CommentListForRestaurantForGuest',
          'UserForGuest',
          'PostAccessForOwn',
          'RestaurantAccessForOwn',
          'UserForOwn',
          'RestaurantForOwn',
          'RestaurantForSetting',
          'UserForSetting',
          'PostForToggle',
          'RestaurantForToggle',
          'RestaurantForView',
          'PostForView',
          'BanquetHallForView',
          'ConferenceHallForView',
          'UserForView',
          'MenuForView',
          'MenuSectionForView',
        ],
        interfaces: [],
      },
    },
  },
  fragments: {},
  operation: {
    kind: 'OperationDefinition',
    operation: 'query',
    variableDefinitions: [],
    directives: [],
    selectionSet: {
      kind: 'SelectionSet',
      selections: [
        {
          kind: 'Field',
          name: { kind: 'Name', value: 'node', loc: { start: 16, end: 20 } },
          arguments: [
            {
              kind: 'Argument',
              name: { kind: 'Name', value: 'id', loc: { start: 21, end: 23 } },
              value: {
                kind: 'StringValue',
                value: 'NWYxMDEzMTQ4NGZiYjIwMDNiZjFiNTkxOlJlc3RhdXJhbnQ6Rm9yVmlldw==',
                block: false,
                loc: { start: 25, end: 87 },
              },
              loc: { start: 21, end: 87 },
            },
          ],
          directives: [],
          selectionSet: {
            kind: 'SelectionSet',
            selections: [
              {
                kind: 'Field',
                name: { kind: 'Name', value: 'id', loc: { start: 95, end: 97 } },
                arguments: [],
                directives: [],
                loc: { start: 95, end: 97 },
              },
              {
                kind: 'InlineFragment',
                typeCondition: {
                  kind: 'NamedType',
                  name: { kind: 'Name', value: 'RestaurantForView', loc: { start: 109, end: 126 } },
                  loc: { start: 109, end: 126 },
                },
                directives: [],
                selectionSet: {
                  kind: 'SelectionSet',
                  selections: [
                    {
                      kind: 'Field',
                      name: { kind: 'Name', value: 'ukTitle', loc: { start: 135, end: 142 } },
                      arguments: [],
                      directives: [],
                      loc: { start: 135, end: 142 },
                    },
                    {
                      kind: 'Field',
                      name: { kind: 'Name', value: 'commentList', loc: { start: 149, end: 160 } },
                      arguments: [],
                      directives: [],
                      selectionSet: {
                        kind: 'SelectionSet',
                        selections: [
                          {
                            kind: 'Field',
                            name: { kind: 'Name', value: 'id', loc: { start: 171, end: 173 } },
                            arguments: [],
                            directives: [],
                            loc: { start: 171, end: 173 },
                          },
                        ],
                        loc: { start: 161, end: 181 },
                      },
                      loc: { start: 149, end: 181 },
                    },
                    {
                      kind: 'Field',
                      name: { kind: 'Name', value: 'banquetHall', loc: { start: 188, end: 199 } },
                      arguments: [],
                      directives: [],
                      selectionSet: {
                        kind: 'SelectionSet',
                        selections: [
                          {
                            kind: 'Field',
                            name: { kind: 'Name', value: 'id', loc: { start: 210, end: 212 } },
                            arguments: [],
                            directives: [],
                            loc: { start: 210, end: 212 },
                          },
                        ],
                        loc: { start: 200, end: 220 },
                      },
                      loc: { start: 188, end: 220 },
                    },
                    {
                      kind: 'Field',
                      name: {
                        kind: 'Name',
                        value: 'conferenceHall',
                        loc: { start: 227, end: 241 },
                      },
                      arguments: [],
                      directives: [],
                      selectionSet: {
                        kind: 'SelectionSet',
                        selections: [
                          {
                            kind: 'Field',
                            name: { kind: 'Name', value: 'id', loc: { start: 252, end: 254 } },
                            arguments: [],
                            directives: [],
                            loc: { start: 252, end: 254 },
                          },
                        ],
                        loc: { start: 242, end: 262 },
                      },
                      loc: { start: 227, end: 262 },
                    },
                    {
                      kind: 'Field',
                      name: { kind: 'Name', value: 'menu', loc: { start: 269, end: 273 } },
                      arguments: [],
                      directives: [],
                      selectionSet: {
                        kind: 'SelectionSet',
                        selections: [
                          {
                            kind: 'Field',
                            name: { kind: 'Name', value: 'id', loc: { start: 284, end: 286 } },
                            arguments: [],
                            directives: [],
                            loc: { start: 284, end: 286 },
                          },
                        ],
                        loc: { start: 274, end: 294 },
                      },
                      loc: { start: 269, end: 294 },
                    },
                  ],
                  loc: { start: 127, end: 300 },
                },
                loc: { start: 102, end: 300 },
              },
            ],
            loc: { start: 89, end: 304 },
          },
          loc: { start: 16, end: 304 },
        },
      ],
      loc: { start: 12, end: 306 },
    },
    loc: { start: 12, end: 306 },
  },
  variableValues: {},
  cacheControl: { cacheHint: {} },
} as unknown as SintheticResolverInfo;

export default info;
